<!DOCTYPE html>
<html lang="es"><head>
<script src="preprocesamiento_files/libs/quarto-html/tabby.min.js"></script>
<script src="preprocesamiento_files/libs/quarto-html/popper.min.js"></script>
<script src="preprocesamiento_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="preprocesamiento_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="preprocesamiento_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="preprocesamiento_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Andrés Felipe Puerta Vélez">
  <title>Preprocesamiento de datos</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="preprocesamiento_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="preprocesamiento_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="preprocesamiento_files/libs/revealjs/dist/theme/quarto-99996581c0bee1b716660960a8445317.css">
  <link href="preprocesamiento_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="preprocesamiento_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="preprocesamiento_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="preprocesamiento_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="preprocesamiento_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="preprocesamiento_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section class="quarto-title-block center">
  <h1 class="title">Preprocesamiento de datos</h1>
  <p class="subtitle">Curso: Machine learning — aprendizaje supervisado de regresión en Python</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Andrés Felipe Puerta Vélez 
</div>
</div>
</div>

  <p class="date">1 de agosto de 2026</p>
</section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>Sesión 2</h1>
<p>Antes de entrenar cualquier modelo hay que dejar los datos en condiciones</p>
</section>
<section class="slide level2">
<h2>Qué veremos hoy</h2>
<ol type="1">
<li><strong>Primer contacto</strong> — mirar los datos antes de tocarlos.</li>
<li><strong>Valores faltantes</strong> — detectarlos, entenderlos, eliminarlos o imputarlos.</li>
<li><strong>Partir en entrenamiento y prueba</strong> — y por qué va <em>antes</em> que casi todo.</li>
<li><strong>Variables categóricas</strong> — label, ordinal y one-hot encoding.</li>
<li><strong>Agrupación</strong> — <code>groupby</code>, categorías raras y discretización.</li>
<li><strong>Escalado</strong> — normalización, estandarización y escalado robusto.</li>
<li><strong>Transformaciones</strong> — qué hacer con una variable sesgada.</li>
<li><strong>La foto completa</strong> — todo el recorrido en una tabla.</li>
</ol>
<div class="destacado">
<p>Al cerrar <strong>cada uno</strong> de los ocho capítulos pararemos a medir, con una regresión lineal y una red neuronal, mirando MSE y <span class="math inline">\(R^2\)</span>. Así se ve paso a paso qué aporta cada decisión — y que no aporta lo mismo a los dos modelos.</p>
</div>
<p>Hoy <strong>sí</strong> hay código. Abran el cuaderno y ejecuten conmigo.</p>
</section>
<section class="slide level2">
<h2>La frase que van a oír toda la vida</h2>
<div class="destacado">
<p>En un proyecto real, entre el <strong>60 % y el 80 %</strong> del tiempo se va en conseguir, limpiar y preparar los datos. El modelo es la parte corta.</p>
</div>
<p>No es una queja: es donde está casi todo el valor. Hoy vamos a ver una red neuronal con un <span class="math inline">\(R^2\)</span> de <strong>−377</strong> —o sea, peor que no hacer nada— y cómo <strong>una sola línea</strong> de preprocesamiento la deja en <strong>+0,449</strong>, sin tocarle un parámetro ni una neurona.</p>
</section>
<section class="slide level2">
<h2>Los dos conjuntos de datos de hoy</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Cars93</strong> · 93 filas × 27 columnas 93 automóviles a la venta en EE. UU. en 1993. Queremos predecir el <strong>precio</strong>. Tiene vacíos de verdad y categóricas de todo tipo. Cabe en pantalla, así que podemos ir viendo la tabla entera.</p>
</div>
<div class="tarjeta">
<p><strong>diamonds</strong> · 53.940 filas × 10 columnas Precios de diamantes. Aporta lo que a Cars93 le falta: <strong>categóricas ordinales reales</strong> (calidad del tallado, color, pureza) y volumen suficiente para que se note el coste de cada decisión.</p>
</div>
</div>
<p>Los dos vienen de paquetes clásicos de R. Están junto al cuaderno, en la carpeta <code>data/</code>, así que una vez descargados <strong>corren sin conexión</strong>.</p>
</section>
<section class="slide level2">
<h2>Cargar los datos</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb1-1"><a href=""></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href=""></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href=""></a></span>
<span id="cb1-4"><a href=""></a>URL <span class="op">=</span> <span class="st">"https://afpuertav.github.io/courses/machine_learning_regresion/Preprocesamiento/data/"</span></span>
<span id="cb1-5"><a href=""></a></span>
<span id="cb1-6"><a href=""></a><span class="kw">def</span> cargar(nombre):</span>
<span id="cb1-7"><a href=""></a>    <span class="co">"""Lee de la carpeta data/ si está; si no, de la web del curso."""</span></span>
<span id="cb1-8"><a href=""></a>    <span class="cf">try</span>:</span>
<span id="cb1-9"><a href=""></a>        <span class="cf">return</span> pd.read_csv(<span class="st">"data/"</span> <span class="op">+</span> nombre)</span>
<span id="cb1-10"><a href=""></a>    <span class="cf">except</span> <span class="pp">FileNotFoundError</span>:</span>
<span id="cb1-11"><a href=""></a>        <span class="cf">return</span> pd.read_csv(URL <span class="op">+</span> nombre)</span>
<span id="cb1-12"><a href=""></a></span>
<span id="cb1-13"><a href=""></a>cars <span class="op">=</span> cargar(<span class="st">"cars93.csv"</span>)</span>
<span id="cb1-14"><a href=""></a>dia  <span class="op">=</span> cargar(<span class="st">"diamonds.csv.gz"</span>)</span>
<span id="cb1-15"><a href=""></a></span>
<span id="cb1-16"><a href=""></a><span class="bu">print</span>(cars.shape, dia.shape)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>(93, 27) (53940, 10)</pre>
</div>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>1 · Primer contacto</h1>
<p>Mirar antes de tocar</p>
</section>
<section class="slide level2">
<h2>Nunca empiecen por el modelo</h2>
<div class="alerta">
<p>Antes de transformar nada: <strong>miren los datos</strong>. Cuántas filas, qué columnas, de qué tipo, qué falta y qué valores raros hay.</p>
</div>
<p>Casi todos los errores caros del preprocesamiento son errores de no haber mirado: una columna que era texto y parecía número, un <code>-999</code> que significaba “no medido”, una fecha en formato americano.</p>
<p>Ninguno de esos errores da un mensaje de error. Dan un modelo que funciona peor y nadie sabe por qué.</p>
</section>
<section class="slide level2">
<h2>Las cuatro órdenes de siempre</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb2-1"><a href=""></a>cars.shape        <span class="co"># cuántas filas y columnas</span></span>
<span id="cb2-2"><a href=""></a>cars.head()       <span class="co"># las primeras filas</span></span>
<span id="cb2-3"><a href=""></a>cars.info()       <span class="co"># tipos y no-nulos por columna</span></span>
<span id="cb2-4"><a href=""></a>cars.describe()   <span class="co"># resumen numérico</span></span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        93 non-null     object 
 1   Model               93 non-null     object 
 2   Type                93 non-null     object 
 3   Min.Price           93 non-null     float64
 4   Price               93 non-null     float64
 5   Max.Price           93 non-null     float64
 6   MPG.city            93 non-null     int64  
 7   MPG.highway         93 non-null     int64  
 8   AirBags             59 non-null     object 
 9   DriveTrain          93 non-null     object 
 10  Cylinders           93 non-null     object 
 11  EngineSize          93 non-null     float64
 12  Horsepower          93 non-null     int64  
 13  RPM                 93 non-null     int64  
 14  Rev.per.mile        93 non-null     int64  
 15  Man.trans.avail     93 non-null     object 
 16  Fuel.tank.capacity  93 non-null     float64
 17  Passengers          93 non-null     int64  
 18  Length              93 non-null     int64  
 19  Wheelbase           93 non-null     int64  
 20  Width               93 non-null     int64  
 21  Turn.circle         93 non-null     int64  
 22  Rear.seat.room      91 non-null     float64
 23  Luggage.room        82 non-null     float64
 24  Weight              93 non-null     int64  
 25  Origin              93 non-null     object 
 26  Make                93 non-null     object 
dtypes: float64(7), int64(11), object(9)
memory usage: 19.7+ KB
       Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers      Length   Wheelbase      Width  Turn.circle  Rear.seat.room  Luggage.room       Weight
count  93.000000  93.000000  93.000000  93.000000    93.000000   93.000000   93.000000    93.000000     93.000000           93.000000   93.000000   93.000000   93.000000  93.000000    93.000000       91.000000     82.000000    93.000000
mean   17.125806  19.509677  21.898925  22.365591    29.086022    2.667742  143.827957  5280.645161   2332.204301           16.664516    5.086022  183.204301  103.946237  69.376344    38.956989       27.829670     13.890244  3072.903226
std     8.746029   9.659430  11.030457   5.619812     5.331726    1.037363   52.374410   596.731690    496.506525            3.279370    1.038979   14.602382    6.819674   3.778986     3.223265        2.989072      2.997967   589.896510
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   55.000000  3800.000000   1320.000000            9.200000    2.000000  141.000000   90.000000  60.000000    32.000000       19.000000      6.000000  1695.000000
25%    10.800000  12.200000  14.700000  18.000000    26.000000    1.800000  103.000000  4800.000000   1985.000000           14.500000    4.000000  174.000000   98.000000  67.000000    37.000000       26.000000     12.000000  2620.000000
50%    14.700000  17.700000  19.600000  21.000000    28.000000    2.400000  140.000000  5200.000000   2340.000000           16.400000    5.000000  183.000000  103.000000  69.000000    39.000000       27.500000     14.000000  3040.000000
75%    20.300000  23.300000  25.300000  25.000000    31.000000    3.300000  170.000000  5750.000000   2565.000000           18.800000    6.000000  192.000000  110.000000  72.000000    41.000000       30.000000     15.000000  3525.000000
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000  300.000000  6500.000000   3755.000000           27.000000    8.000000  219.000000  119.000000  78.000000    45.000000       36.000000     22.000000  4105.000000</pre>
</div>
</section>
<section class="slide level2">
<h2>El primer diagnóstico: <code>info()</code></h2>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb3-1"><a href=""></a>cars[[<span class="st">"Manufacturer"</span>, <span class="st">"Type"</span>, <span class="st">"Price"</span>, <span class="st">"AirBags"</span>,</span>
<span id="cb3-2"><a href=""></a>      <span class="st">"Cylinders"</span>, <span class="st">"Horsepower"</span>, <span class="st">"Luggage.room"</span>, <span class="st">"Origin"</span>]].info()</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 93 entries, 0 to 92
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Manufacturer  93 non-null     object 
 1   Type          93 non-null     object 
 2   Price         93 non-null     float64
 3   AirBags       59 non-null     object 
 4   Cylinders     93 non-null     object 
 5   Horsepower    93 non-null     int64  
 6   Luggage.room  82 non-null     float64
 7   Origin        93 non-null     object 
dtypes: float64(2), int64(1), object(5)
memory usage: 5.9+ KB</pre>
</div>
<p>Dos cosas saltan: <strong><code>AirBags</code> solo tiene 59 de 93</strong> y <strong><code>Cylinders</code> es texto</strong> (<code>object</code>) cuando uno esperaría un número.</p>
</section>
<section class="slide level2">
<h2>Órdenes de magnitud muy distintos: <code>describe()</code></h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb4-1"><a href=""></a>cars[[<span class="st">"Price"</span>, <span class="st">"MPG.city"</span>, <span class="st">"Horsepower"</span>, <span class="st">"Weight"</span>]].describe().<span class="bu">round</span>(<span class="dv">2</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>       Price  MPG.city  Horsepower  Weight
count  93.00     93.00       93.00    93.0
mean   19.51     22.37      143.83  3072.9
std     9.66      5.62       52.37   589.9
min     7.40     15.00       55.00  1695.0
25%    12.20     18.00      103.00  2620.0
50%    17.70     21.00      140.00  3040.0
75%    23.30     25.00      170.00  3525.0
max    61.90     46.00      300.00  4105.0</pre>
</div>
<div class="destacado">
<p><code>Weight</code> vive en los miles y <code>MPG.city</code> en las decenas. Guarden esa idea: es exactamente el problema que resolverá el <strong>escalado</strong>.</p>
</div>
</section>
<section class="slide level2">
<h2>El banco de pruebas</h2>
<p>Al cerrar <strong>cada capítulo</strong> vamos a medir lo mismo, de la misma forma.</p>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Dos modelos</strong> <code>LinearRegression()</code> y una red <code>MLPRegressor</code> de una capa de 32 neuronas. Siempre los mismos, sin tocarles nada entre capítulos.</p>
</div>
<div class="tarjeta">
<p><strong>Dos métricas</strong> <strong>MSE</strong> — error cuadrático medio, en (miles de USD)². <strong>R²</strong> — cuánta variación del precio explica el modelo. 1 es perfecto, 0 es tan bueno como decir la media, y negativo es peor que eso.</p>
</div>
<div class="tarjeta">
<p><strong>Validación cruzada</strong> Cinco pliegues sobre los 93 coches. Con una sola partición de 19 coches las cifras bailan tanto que no se podría comparar nada.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>El código del banco</h2>
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb5-1"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb5-2"><a href=""></a><span class="im">from</span> sklearn.neural_network <span class="im">import</span> MLPRegressor</span>
<span id="cb5-3"><a href=""></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_validate</span>
<span id="cb5-4"><a href=""></a></span>
<span id="cb5-5"><a href=""></a><span class="kw">def</span> modelos():</span>
<span id="cb5-6"><a href=""></a>    <span class="co">"""Los dos del banco. Idénticos en los ocho capítulos."""</span></span>
<span id="cb5-7"><a href=""></a>    <span class="cf">return</span> [(<span class="st">"LinearRegression"</span>, LinearRegression()),</span>
<span id="cb5-8"><a href=""></a>            (<span class="st">"MLPRegressor"</span>, MLPRegressor(hidden_layer_sizes<span class="op">=</span>(<span class="dv">32</span>,),</span>
<span id="cb5-9"><a href=""></a>                                          max_iter<span class="op">=</span><span class="dv">2000</span>,</span>
<span id="cb5-10"><a href=""></a>                                          random_state<span class="op">=</span><span class="dv">7</span>))]</span>
<span id="cb5-11"><a href=""></a></span>
<span id="cb5-12"><a href=""></a>historial <span class="op">=</span> []</span>
<span id="cb5-13"><a href=""></a></span>
<span id="cb5-14"><a href=""></a><span class="kw">def</span> chequeo(capitulo, hacer_tuberia, X, y):</span>
<span id="cb5-15"><a href=""></a>    <span class="co">"""Mide los dos modelos y acumula la fila en el historial.</span></span>
<span id="cb5-16"><a href=""></a></span>
<span id="cb5-17"><a href=""></a><span class="co">    hacer_tuberia(modelo) devuelve lo que hay que evaluar: el modelo</span></span>
<span id="cb5-18"><a href=""></a><span class="co">    a secas, o el modelo dentro de una tubería de preprocesamiento.</span></span>
<span id="cb5-19"><a href=""></a><span class="co">    """</span></span>
<span id="cb5-20"><a href=""></a>    fila <span class="op">=</span> [capitulo]</span>
<span id="cb5-21"><a href=""></a>    <span class="cf">for</span> nombre, modelo <span class="kw">in</span> modelos():</span>
<span id="cb5-22"><a href=""></a>        <span class="cf">try</span>:</span>
<span id="cb5-23"><a href=""></a>            t <span class="op">=</span> hacer_tuberia(modelo)</span>
<span id="cb5-24"><a href=""></a>            <span class="co"># cross_validate saca las dos métricas en una sola pasada.</span></span>
<span id="cb5-25"><a href=""></a>            <span class="co"># error_score="raise" deja pasar el error de verdad; si no,</span></span>
<span id="cb5-26"><a href=""></a>            <span class="co"># sklearn lo tapa con un "All the 5 fits failed".</span></span>
<span id="cb5-27"><a href=""></a>            r <span class="op">=</span> cross_validate(t, X, y, cv<span class="op">=</span><span class="dv">5</span>, error_score<span class="op">=</span><span class="st">"raise"</span>,</span>
<span id="cb5-28"><a href=""></a>                               scoring<span class="op">=</span>[<span class="st">"neg_mean_squared_error"</span>, <span class="st">"r2"</span>])</span>
<span id="cb5-29"><a href=""></a>            fila <span class="op">+=</span> [<span class="bu">round</span>(<span class="op">-</span>r[<span class="st">"test_neg_mean_squared_error"</span>].mean(), <span class="dv">2</span>),</span>
<span id="cb5-30"><a href=""></a>                     <span class="bu">round</span>(r[<span class="st">"test_r2"</span>].mean(), <span class="dv">3</span>)]</span>
<span id="cb5-31"><a href=""></a>        <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb5-32"><a href=""></a>            fila <span class="op">+=</span> [<span class="st">"error"</span>, <span class="st">"error"</span>]</span>
<span id="cb5-33"><a href=""></a>            motivo <span class="op">=</span> <span class="bu">str</span>(e).strip().splitlines()[<span class="dv">0</span>]</span>
<span id="cb5-34"><a href=""></a>            <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span><span class="bu">type</span>(e)<span class="sc">.</span><span class="va">__name__</span><span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>motivo[:<span class="dv">60</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-35"><a href=""></a>    historial.append(fila)</span>
<span id="cb5-36"><a href=""></a>    <span class="cf">return</span> pd.DataFrame(historial, columns<span class="op">=</span>[<span class="st">"capítulo"</span>, <span class="st">"MSE lineal"</span>,</span>
<span id="cb5-37"><a href=""></a>                                            <span class="st">"R2 lineal"</span>, <span class="st">"MSE red"</span>, <span class="st">"R2 red"</span>])</span></code></pre></div>
<div class="destacado">
<p><code>random_state=7</code> fija la inicialización de la red para que el resultado sea reproducible. Todo lo demás se queda igual los ocho capítulos.</p>
</div>
</section>
<section class="slide level2">
<h2>Chequeo 1 · Sin preprocesar nada</h2>
<div class="sourceCode" id="cb6"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb6-1"><a href=""></a><span class="co"># Fuera lo que es el precio disfrazado o un identificador</span></span>
<span id="cb6-2"><a href=""></a>cars_m <span class="op">=</span> cars.drop(columns<span class="op">=</span>[<span class="st">"Min.Price"</span>, <span class="st">"Max.Price"</span>, <span class="st">"Make"</span>, <span class="st">"Model"</span>])</span>
<span id="cb6-3"><a href=""></a></span>
<span id="cb6-4"><a href=""></a>X <span class="op">=</span> cars_m.drop(columns<span class="op">=</span>[<span class="st">"Price"</span>])</span>
<span id="cb6-5"><a href=""></a>y <span class="op">=</span> cars_m[<span class="st">"Price"</span>]</span>
<span id="cb6-6"><a href=""></a></span>
<span id="cb6-7"><a href=""></a>num_cols <span class="op">=</span> X.select_dtypes(include<span class="op">=</span>np.number).columns.tolist()</span>
<span id="cb6-8"><a href=""></a>cat_cols <span class="op">=</span> X.select_dtypes(exclude<span class="op">=</span>np.number).columns.tolist()</span>
<span id="cb6-9"><a href=""></a></span>
<span id="cb6-10"><a href=""></a>chequeo(<span class="st">"1a · Sin tocar nada"</span>, <span class="kw">lambda</span> m: m, X, y)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>  LinearRegression: ValueError: could not convert string to float: 'Chrylser'
  MLPRegressor: ValueError: could not convert string to float: 'Chrylser'
              capítulo MSE lineal R2 lineal MSE red R2 red
0  1a · Sin tocar nada      error     error   error  error</pre>
</div>
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb7-1"><a href=""></a>chequeo(<span class="st">"1b · Solo las numéricas"</span>, <span class="kw">lambda</span> m: m, X[num_cols], y)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>  LinearRegression: ValueError: Input X contains NaN.
  MLPRegressor: ValueError: Input X contains NaN.
                  capítulo MSE lineal R2 lineal MSE red R2 red
0      1a · Sin tocar nada      error     error   error  error
1  1b · Solo las numéricas      error     error   error  error</pre>
</div>
</section>
<section class="slide level2">
<h2>Dos errores, dos capítulos</h2>
<div class="terminal" data-nocopy="">
<pre>capítulo                  MSE lineal  R2 lineal   MSE red   R2 red
1a · Sin tocar nada            error      error     error    error
1b · Solo las numéricas        error      error     error    error</pre>
</div>
<div class="alerta">
<p>No es que el modelo prediga mal: es que <strong>no arranca</strong>. Los dos errores nos marcan el orden del día.</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>could not convert string to float</code></strong> Hay texto donde el modelo espera números. Lo resolveremos en el capítulo 5.</p>
</div>
<div class="tarjeta">
<p><strong><code>Input X contains NaN</code></strong> Hay huecos. Es el capítulo que empieza ahora.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>2 · Valores faltantes</h1>
<p>Lo que no está también dice algo</p>
</section>
<section class="slide level2">
<h2>Por qué hay que ocuparse de esto</h2>
<p>La razón inmediata es que <strong>scikit-learn no acepta vacíos</strong>: la mayoría de sus modelos fallan en cuanto encuentran un <code>NaN</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb8-1"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb8-2"><a href=""></a>LinearRegression().fit(cars[[<span class="st">"Horsepower"</span>, <span class="st">"Luggage.room"</span>]], cars[<span class="st">"Price"</span>])</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>ValueError: Input X contains NaN.</pre>
</div>
<div class="destacado">
<p>La razón de fondo es más interesante: <strong>cómo rellenamos esos huecos cambia lo que el modelo aprende</strong>. No es un trámite para que deje de dar error.</p>
</div>
</section>
<section class="slide level2">
<h2>Detectarlos</h2>
<div class="sourceCode" id="cb9"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb9-1"><a href=""></a>faltan <span class="op">=</span> cars.isna().<span class="bu">sum</span>()</span>
<span id="cb9-2"><a href=""></a><span class="bu">print</span>(faltan[faltan <span class="op">&gt;</span> <span class="dv">0</span>])</span>
<span id="cb9-3"><a href=""></a></span>
<span id="cb9-4"><a href=""></a>pct <span class="op">=</span> (cars.isna().mean() <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb9-5"><a href=""></a><span class="bu">print</span>(pct[pct <span class="op">&gt;</span> <span class="dv">0</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>))</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>AirBags           34
Rear.seat.room     2
Luggage.room      11
dtype: int64
AirBags           36.6
Luggage.room      11.8
Rear.seat.room     2.2
dtype: float64</pre>
</div>
<p>El porcentaje importa más que el conteo: 34 vacíos sobre 93 filas es <strong>más de un tercio de la columna</strong>.</p>
</section>
<section class="slide level2">
<h2>No todos los vacíos son iguales</h2>
<p>Antes de rellenar hay que preguntarse <strong>por qué</strong> falta el dato. La estadística distingue tres mecanismos, y cada uno admite un tratamiento distinto.</p>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>MCAR</strong> <span class="sigla">Missing Completely At Random</span> Falta <strong>completamente al azar</strong>: la ausencia no depende de nada, ni de lo que vemos ni de lo que no vemos. Es el caso cómodo y también el más raro. <em>Ejemplo: se perdió una hoja del cuestionario.</em></p>
</div>
<div class="tarjeta">
<p><strong>MAR</strong> <span class="sigla">Missing At Random</span> Falta <strong>al azar, condicionado a lo observado</strong>: la ausencia depende de otras columnas que <strong>sí</strong> tenemos. <em>Ejemplo: a las furgonetas nunca les midieron el maletero.</em></p>
</div>
<div class="tarjeta">
<p><strong>MNAR</strong> <span class="sigla">Missing Not At Random</span> <strong>No</strong> falta al azar: la ausencia depende del propio valor que falta. El caso peligroso, porque no se puede detectar con los datos que hay. <em>Ejemplo: los de renta alta no declaran su renta.</em></p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Qué implica cada mecanismo</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Si es MCAR</strong> Eliminar las filas es válido: lo que queda sigue siendo una muestra representativa. Imputar con la media tampoco sesga.</p>
</div>
<div class="tarjeta">
<p><strong>Si es MAR</strong> Eliminar <strong>sí</strong> sesga (perderíamos casi todas las furgonetas). Imputar usando las columnas relacionadas —por grupo, o con KNN— es lo correcto.</p>
</div>
<div class="tarjeta">
<p><strong>Si es MNAR</strong> No hay solución estadística limpia. Lo honesto es <strong>añadir una columna que marque que faltaba</strong> y reconocer la limitación en el informe.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Por qué imputar un MNAR introduce sesgo</h2>
<p>Supongamos una encuesta de sueldos donde <strong>los que ganan mucho no responden</strong>. De diez personas responden siete:</p>
<div class="terminal" data-nocopy="">
<pre>sueldos reales     : 1.0  1.2  1.3  1.5  1.6  1.8  2.0  <span class="salida">6.0  7.0  9.0</span>
                                                          ↑ estos tres no responden
sueldos observados : 1.0  1.2  1.3  1.5  1.6  1.8  2.0
media observada    : 1.49
media verdadera    : 3.24</pre>
</div>
<p>La media que calculamos <strong>solo con los que responden</strong> ya está sesgada hacia abajo: es la media de los sueldos bajos. Al imputar 1,49 en los tres huecos, no estamos corrigiendo el sesgo, lo estamos <strong>copiando tres veces más</strong>. La media final baja aún más, a 1,49, cuando la verdadera era 3,24.</p>
</section>
<section class="slide level2">
<h2>Y lo mismo en un modelo</h2>
<div class="alerta">
<p>Imputar con la media asume MCAR. Con MNAR, la media que usamos <strong>está calculada justo sobre las filas que no se parecen a las que faltan</strong>.</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>El error es sistemático</strong> No se compensa con más datos: cuantas más filas MNAR haya, peor. No es ruido, es sesgo.</p>
</div>
<div class="tarjeta">
<p><strong>El modelo aprende una relación falsa</strong> Si a los coches caros les falta el maletero y les ponemos el maletero medio, el modelo concluye que maletero medio y precio alto van juntos.</p>
</div>
<div class="tarjeta">
<p><strong>Y encima parece que funciona</strong> Los vacíos desaparecen, el código corre y las métricas de entrenamiento no se quejan de nada.</p>
</div>
</div>
<p>La única salida honesta es <strong>marcar que faltaba</strong> con una columna 0/1 y decirlo en el informe.</p>
</section>
<section class="slide level2">
<h2>El caso de <code>AirBags</code></h2>
<div class="sourceCode" id="cb10"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb10-1"><a href=""></a>cars[<span class="st">"AirBags"</span>].value_counts(dropna<span class="op">=</span><span class="va">False</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>AirBags
Driver only           43
NaN                   34
Driver &amp; Passenger    16</pre>
</div>
<div class="concepto">
<p>Aquí el <code>NaN</code> <strong>no es un dato perdido</strong>: es el coche que no traía airbag. En el original esa categoría era <code>"None"</code> y al leerla se convirtió en vacío.</p>
</div>
<p>Imputar esos 34 con la moda sería inventarse 34 airbags que no existen.</p>
</section>
<section class="slide level2">
<h2>Lección: pregunten qué significa el vacío</h2>
<p>Antes de imputar, la pregunta no es <em>“¿con qué lo relleno?”</em> sino <strong>“¿por qué no está?”</strong>.</p>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>No se midió</strong> Imputar tiene sentido.</p>
</div>
<div class="tarjeta">
<p><strong>No aplica</strong> Es una categoría, no un vacío. <code>"No aplica"</code>.</p>
</div>
<div class="tarjeta">
<p><strong>Se perdió</strong> Imputar, y dejar constancia de que ese dato es reconstruido.</p>
</div>
<div class="tarjeta">
<p><strong>Es un cero mal codificado</strong> Se corrige, no se imputa.</p>
</div>
</div>
<p>Muchas veces la respuesta está en el diccionario de datos, no en el código.</p>
</section>
<section class="slide level2">
<h2>Opción 1 · Eliminar</h2>
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb11-1"><a href=""></a><span class="bu">print</span>(<span class="st">"original        "</span>, cars.shape)</span>
<span id="cb11-2"><a href=""></a><span class="bu">print</span>(<span class="st">"dropna() filas  "</span>, cars.dropna().shape)</span>
<span id="cb11-3"><a href=""></a><span class="bu">print</span>(<span class="st">"dropna(axis=1)  "</span>, cars.dropna(axis<span class="op">=</span><span class="dv">1</span>).shape)</span>
<span id="cb11-4"><a href=""></a>minimo <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.9</span> <span class="op">*</span> <span class="bu">len</span>(cars))</span>
<span id="cb11-5"><a href=""></a><span class="bu">print</span>(<span class="st">"thresh 90</span><span class="sc">% c</span><span class="st">ols "</span>, cars.dropna(axis<span class="op">=</span><span class="dv">1</span>, thresh<span class="op">=</span>minimo).shape)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>original         (93, 27)
dropna() filas   (54, 27)
dropna(axis=1)   (93, 24)
thresh 90% cols  (93, 25)</pre>
</div>
<div class="alerta">
<p><code>dropna()</code> nos deja <strong>54 de 93 filas</strong>: perdemos el 42 % de los datos por culpa de tres columnas. Casi nunca es la opción correcta.</p>
</div>
</section>
<section class="slide level2">
<h2>¿Cuándo sí eliminar?</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Eliminar la columna</strong> Cuando falta muchísimo (&gt;50-60 %) y no es clave. Lo que quede no sostiene una imputación creíble.</p>
</div>
<div class="tarjeta">
<p><strong>Eliminar la fila</strong> Cuando son poquísimas filas (&lt;2-5 %) y el faltante es MCAR.</p>
</div>
<div class="tarjeta">
<p><strong>Eliminar la fila, siempre</strong> Si lo que falta es la <strong>variable objetivo</strong>. No se imputa lo que hay que predecir: sería inventarse la respuesta.</p>
</div>
<div class="tarjeta">
<p><strong>No eliminar</strong> Cuando el hecho de faltar es informativo. Ahí conviene una columna <code>_faltaba</code> de 0 y 1.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Opción 2 · Imputar: ¿media, mediana o moda?</h2>
<div class="sourceCode" id="cb12"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb12-1"><a href=""></a>lr <span class="op">=</span> cars[<span class="st">"Luggage.room"</span>]</span>
<span id="cb12-2"><a href=""></a><span class="bu">print</span>(<span class="ss">f"media    </span><span class="sc">{</span>lr<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb12-3"><a href=""></a><span class="bu">print</span>(<span class="ss">f"mediana  </span><span class="sc">{</span>lr<span class="sc">.</span>median()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb12-4"><a href=""></a><span class="bu">print</span>(<span class="ss">f"moda     </span><span class="sc">{</span>lr<span class="sc">.</span>mode()[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>media    13.890
mediana  14.000
moda     14.000</pre>
</div>
<div class="destacado">
<p>Aquí dan casi lo mismo porque la variable es simétrica. En una variable sesgada (ingresos, precios) la <strong>media se va detrás de los atípicos</strong> y la mediana es la opción segura.</p>
</div>
<p>Regla práctica: <strong>numérica simétrica → media; numérica sesgada → mediana; categórica → moda o una categoría nueva</strong>.</p>
</section>
<section class="slide level2">
<h2>Chequeo 2 · Eliminando los vacíos</h2>
<p>Nos quedamos con las numéricas y tiramos las filas incompletas: sobreviven <strong>82 coches de 93</strong>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb13-1"><a href=""></a>X_limpio <span class="op">=</span> X[num_cols].dropna()</span>
<span id="cb13-2"><a href=""></a>y_limpio <span class="op">=</span> y.loc[X_limpio.index]</span>
<span id="cb13-3"><a href=""></a><span class="bu">print</span>(<span class="st">"filas que sobreviven:"</span>, <span class="bu">len</span>(X_limpio), <span class="st">"de"</span>, <span class="bu">len</span>(X))</span>
<span id="cb13-4"><a href=""></a></span>
<span id="cb13-5"><a href=""></a>chequeo(<span class="st">"2 · dropna sobre las numéricas"</span>, <span class="kw">lambda</span> m: m, X_limpio, y_limpio)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>filas que sobreviven: 82 de 93
                         capítulo MSE lineal R2 lineal   MSE red   R2 red
0             1a · Sin tocar nada      error     error     error    error
1         1b · Solo las numéricas      error     error     error    error
2  2 · dropna sobre las numéricas      46.77     0.295  68165.39 -1015.81</pre>
</div>
</section>
<section class="slide level2">
<h2>Ya tenemos números, y no son buenos</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>La lineal arranca</strong> <span class="math inline">\(R^2 = 0{,}295\)</span>. Explica menos de un tercio de la variación del precio, pero al menos funciona.</p>
</div>
<div class="tarjeta">
<p><strong>La red es un desastre</strong> <span class="math inline">\(R^2 = -1015\)</span>. Un negativo ya significa peor que predecir siempre la media; con esa magnitud, el error es de otro orden que los precios. En el capítulo 7 abriremos la red para ver por qué.</p>
</div>
<div class="tarjeta">
<p><strong>Y hemos perdido 11 coches</strong> Un 12 % de los datos, tirado por culpa de dos columnas incompletas.</p>
</div>
</div>
<p>Los tres problemas tienen arreglo. Vamos con ellos por orden.</p>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>3 · Partir antes de transformar</h1>
<p>El error más caro de todos</p>
</section>
<section class="slide level2">
<h2>La fuga de datos</h2>
<div class="concepto">
<p>Hay <strong>fuga de datos</strong> (<em>data leakage</em>) cuando en el entrenamiento se cuela información que en el momento de predecir no estaría disponible. El resultado es un modelo que parece buenísimo en pruebas y fracasa en producción.</p>
</div>
<p>Imputar con la media de <strong>todo</strong> el dataset es fuga: esa media contiene información de las filas de prueba, que se supone que aún no hemos visto.</p>
</section>
<section class="slide level2">
<h2>Se ve con números</h2>
<div class="sourceCode" id="cb14"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb14-1"><a href=""></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb14-2"><a href=""></a></span>
<span id="cb14-3"><a href=""></a><span class="co"># X e y son los del banco de pruebas, ya sin las columnas</span></span>
<span id="cb14-4"><a href=""></a><span class="co"># que eran el precio disfrazado</span></span>
<span id="cb14-5"><a href=""></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb14-6"><a href=""></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb14-7"><a href=""></a></span>
<span id="cb14-8"><a href=""></a><span class="bu">print</span>(<span class="st">"X_train"</span>, X_train.shape, <span class="st">" X_test"</span>, X_test.shape)</span>
<span id="cb14-9"><a href=""></a><span class="bu">print</span>(<span class="ss">f"media de Luggage.room en TODO   : </span><span class="sc">{</span>X[<span class="st">'Luggage.room'</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb14-10"><a href=""></a><span class="bu">print</span>(<span class="ss">f"media de Luggage.room solo train: </span><span class="sc">{</span>X_train[<span class="st">'Luggage.room'</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>X_train (74, 22)  X_test (19, 22)
media de Luggage.room en TODO   : 13.890
media de Luggage.room solo train: 14.212</pre>
</div>
<p>Son valores distintos. Usar el primero para rellenar el conjunto de prueba significa que la prueba ya sabe algo de sí misma.</p>
</section>
<section class="slide level2">
<h2>La regla, en una frase</h2>
<div class="alerta">
<p><strong>Todo lo que aprenda un parámetro de los datos</strong> —medias, medianas, mínimos, máximos, categorías, desviaciones— se ajusta <strong>solo con entrenamiento</strong> y se aplica a prueba.</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>fit</code> en train</strong> Aprende los parámetros y los guarda dentro del objeto.</p>
</div>
<div class="tarjeta">
<p><strong><code>transform</code> en train y en test</strong> Aplica lo aprendido, sin volver a aprender.</p>
</div>
<div class="tarjeta">
<p><strong>Nunca <code>fit</code> en test</strong> Ni <code>fit_transform</code>. Es el error clásico y no da ningún aviso.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>El orden correcto</h2>
<ol type="1">
<li>Cargar los datos y <strong>mirarlos</strong>.</li>
<li>Arreglar lo que es objetivamente un error: tipos, duplicados, unidades.</li>
<li><strong>Partir en entrenamiento y prueba.</strong></li>
<li><code>fit</code> de imputadores, codificadores y escaladores <strong>con entrenamiento</strong>.</li>
<li><code>transform</code> de ambos conjuntos.</li>
<li>Entrenar y evaluar.</li>
</ol>
<div class="destacado">
<p>El paso 2 puede ir antes de partir porque <strong>no aprende nada de los datos</strong>: convertir texto a número o quitar duplicados no depende de qué filas nos tocaron.</p>
</div>
</section>
<section class="slide level2">
<h2>Chequeo 3 · Con fuga y sin fuga</h2>
<p>Rellenamos con la mediana de dos maneras: calculándola con <strong>todo</strong> el dataset (fuga) y calculándola <strong>dentro</strong> de la validación cruzada (correcto).</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb15-1"><a href=""></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb15-2"><a href=""></a><span class="im">from</span> sklearn.impute <span class="im">import</span> SimpleImputer</span>
<span id="cb15-3"><a href=""></a></span>
<span id="cb15-4"><a href=""></a><span class="co"># con fuga: esta mediana ve los cinco pliegues</span></span>
<span id="cb15-5"><a href=""></a>X_fuga <span class="op">=</span> X[num_cols].fillna(X[num_cols].median())</span>
<span id="cb15-6"><a href=""></a>chequeo(<span class="st">"3a · Imputando fuera (con fuga)"</span>, <span class="kw">lambda</span> m: m, X_fuga, y)</span>
<span id="cb15-7"><a href=""></a></span>
<span id="cb15-8"><a href=""></a><span class="co"># correcto: la mediana se recalcula dentro de cada pliegue</span></span>
<span id="cb15-9"><a href=""></a>chequeo(<span class="st">"3b · Imputando dentro (correcto)"</span>,</span>
<span id="cb15-10"><a href=""></a>        <span class="kw">lambda</span> m: Pipeline([(<span class="st">"imp"</span>, SimpleImputer(strategy<span class="op">=</span><span class="st">"median"</span>)),</span>
<span id="cb15-11"><a href=""></a>                            (<span class="st">"reg"</span>, m)]),</span>
<span id="cb15-12"><a href=""></a>        X[num_cols], y)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>                           capítulo MSE lineal R2 lineal   MSE red    R2 red
0               1a · Sin tocar nada      error     error     error     error
1           1b · Solo las numéricas      error     error     error     error
2    2 · dropna sobre las numéricas      46.77     0.295  68165.39  -1015.81
3   3a · Imputando fuera (con fuga)      37.39      0.44  71652.15 -1132.738
4  3b · Imputando dentro (correcto)      37.39      0.44  71652.37 -1132.739</pre>
</div>
</section>
<section class="slide level2">
<h2>Salen iguales. Y eso es justo lo peligroso</h2>
<div class="alerta">
<p>La fuga <strong>no se nota en las métricas</strong>. Si se notara, la cazaríamos enseguida: el problema es que se cuela sin dejar rastro.</p>
</div>
<p>Aquí no cambia nada porque la mediana es muy robusta: quitar 20 coches apenas la mueve. Pero el mismo error con otras técnicas sí hace daño:</p>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Target encoding</strong> La media del objetivo por categoría se contamina de lleno con las filas de prueba.</p>
</div>
<div class="tarjeta">
<p><strong>Selección de variables</strong> Elegir columnas mirando todo el dataset ya es haber usado el conjunto de prueba.</p>
</div>
<div class="tarjeta">
<p><strong>Escalado con atípicos</strong> Un solo valor extremo en prueba mueve el mínimo y el máximo.</p>
</div>
</div>
<p>La regla no se sigue porque se vea el daño, sino <strong>porque no se ve</strong>.</p>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>4 · Imputar en serio</h1>
<p>Ahora sí, con el conjunto ya partido</p>
</section>
<section class="slide level2">
<h2><code>SimpleImputer</code>: la versión de scikit-learn</h2>
<p>Hacerlo con pandas funciona, pero deja los valores de relleno sueltos en una variable. <code>SimpleImputer</code> los <strong>guarda dentro del objeto</strong>, y eso es lo que permite aplicar exactamente lo mismo al conjunto de prueba y a producción.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb16-1"><a href=""></a><span class="co"># estrategias: "mean", "median", "most_frequent", "constant"</span></span>
<span id="cb16-2"><a href=""></a>imp_num <span class="op">=</span> SimpleImputer(strategy<span class="op">=</span><span class="st">"median"</span>)</span>
<span id="cb16-3"><a href=""></a>imp_num.fit(X_train[num_cols])</span>
<span id="cb16-4"><a href=""></a></span>
<span id="cb16-5"><a href=""></a>pd.Series(imp_num.statistics_, index<span class="op">=</span>num_cols)[[<span class="st">"Rear.seat.room"</span>, <span class="st">"Luggage.room"</span>]]</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>Rear.seat.room    28.0
Luggage.room      14.0</pre>
</div>
</section>
<section class="slide level2">
<h2>Imputar categóricas</h2>
<div class="sourceCode" id="cb17"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb17-1"><a href=""></a>imp_cat <span class="op">=</span> SimpleImputer(strategy<span class="op">=</span><span class="st">"constant"</span>, fill_value<span class="op">=</span><span class="st">"Sin airbag"</span>)</span>
<span id="cb17-2"><a href=""></a>Xtr_cat <span class="op">=</span> pd.DataFrame(imp_cat.fit_transform(X_train[cat_cols]),</span>
<span id="cb17-3"><a href=""></a>                       columns<span class="op">=</span>cat_cols, index<span class="op">=</span>X_train.index)</span>
<span id="cb17-4"><a href=""></a></span>
<span id="cb17-5"><a href=""></a>Xtr_cat[<span class="st">"AirBags"</span>].value_counts()</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>AirBags
Driver only           35
Sin airbag            26
Driver &amp; Passenger    13</pre>
</div>
<p>Con <code>strategy="constant"</code> creamos una categoría explícita en lugar de disfrazar los vacíos de moda. Es justo lo que pedía el caso de <code>AirBags</code>.</p>
</section>
<section class="slide level2">
<h2>Imputación avanzada: <code>KNNImputer</code></h2>
<p>En vez de un único valor para todos, busca los <strong>k coches más parecidos</strong> en las demás columnas y promedia su valor. Sirve cuando el faltante es MAR: aprovecha precisamente esas columnas de las que depende la ausencia.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb18-1"><a href=""></a><span class="im">from</span> sklearn.impute <span class="im">import</span> KNNImputer</span>
<span id="cb18-2"><a href=""></a></span>
<span id="cb18-3"><a href=""></a>knn <span class="op">=</span> KNNImputer(n_neighbors<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb18-4"><a href=""></a>Xtr_knn <span class="op">=</span> pd.DataFrame(knn.fit_transform(X_train[num_cols]),</span>
<span id="cb18-5"><a href=""></a>                       columns<span class="op">=</span>num_cols, index<span class="op">=</span>X_train.index)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>    mediana   knn
65     14.0  17.6
15     14.0  16.6
69     14.0  16.6
16     14.0  19.0</pre>
</div>
<div class="destacado">
<p>La mediana pone 14 a todos. El KNN nota que esos cuatro son coches grandes y les pone entre 16 y 19. Más fiel, pero más lento y <strong>exige escalar antes</strong>, porque el vecindario se mide con distancias.</p>
</div>
</section>
<section class="slide level2">
<h2>Imputar por grupo, y su trampa</h2>
<div class="sourceCode" id="cb19"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb19-1"><a href=""></a>cars.groupby(<span class="st">"Type"</span>)[<span class="st">"Luggage.room"</span>].median()</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>Type
Compact    14.0
Large      18.0
Midsize    15.0
Small      12.0
Sporty     11.5
Van         NaN</pre>
</div>
<div class="alerta">
<p><code>Van</code> sale <code>NaN</code>: <strong>a las nueve furgonetas les falta el dato a todas</strong>. Si el grupo entero está vacío, la imputación por grupo no rellena nada y hay que caer en un valor global.</p>
</div>
<p>Y de paso confirma que el faltante era MAR: depende de <code>Type</code>, que sí observamos.</p>
</section>
<section class="slide level2">
<h2>El catálogo completo</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>IterativeImputer</code></strong> Modela cada columna con vacíos a partir de las demás, e itera hasta converger. Lo más potente y lo más caro.</p>
</div>
<div class="tarjeta">
<p><strong>Indicador de faltante</strong> <code>SimpleImputer(add_indicator=True)</code> añade una columna 0/1. Deja que el modelo aprenda si el hecho de faltar significa algo.</p>
</div>
<div class="tarjeta">
<p><strong>No imputar</strong> <code>HistGradientBoostingRegressor</code>, LightGBM y XGBoost manejan <code>NaN</code> de forma nativa y suelen hacerlo mejor que cualquier imputación.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Chequeo 4 · Con imputación</h2>
<div class="sourceCode" id="cb20"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb20-1"><a href=""></a>chequeo(<span class="st">"4 · SimpleImputer(mediana)"</span>,</span>
<span id="cb20-2"><a href=""></a>        <span class="kw">lambda</span> m: Pipeline([(<span class="st">"imp"</span>, SimpleImputer(strategy<span class="op">=</span><span class="st">"median"</span>)),</span>
<span id="cb20-3"><a href=""></a>                            (<span class="st">"reg"</span>, m)]),</span>
<span id="cb20-4"><a href=""></a>        X[num_cols], y)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>capítulo                        MSE lineal  R2 lineal    MSE red     R2 red
2 · dropna sobre las numéricas       46.77      0.295   68165.39  -1015.810
4 · SimpleImputer(mediana)           <span class="salida">37.39      0.440</span>   71652.37  -1132.739</pre>
</div>
<div class="destacado">
<p>La lineal mejora de verdad: el MSE baja de 46,77 a 37,39 y el <span class="math inline">\(R^2\)</span> sube de 0,295 a 0,440. No porque imputar sea mágico, sino porque <strong>entrenamos con 93 coches en vez de 82</strong>.</p>
</div>
<p>La red sigue igual de rota. Su problema es otro y todavía no lo hemos tocado.</p>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>5 · Variables categóricas</h1>
<p>Los modelos solo entienden números</p>
</section>
<section class="slide level2">
<h2>Por qué hay que codificar</h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb21-1"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb21-2"><a href=""></a>LinearRegression().fit(X_train, y_train)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>ValueError: could not convert string to float: 'Nissan'</pre>
</div>
<div class="concepto">
<p>Un modelo de regresión multiplica cada columna por un coeficiente y suma. La palabra <code>"Nissan"</code> no se puede multiplicar por nada. <strong>Codificar</strong> es convertir esas etiquetas en números <strong>sin inventarse relaciones que no existen</strong>.</p>
</div>
<p>Esa última condición es toda la dificultad del asunto.</p>
</section>
<section class="slide level2">
<h2>Tres tipos de categórica</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Nominal</strong> Sin orden. <code>Type</code>, <code>Manufacturer</code>, <code>DriveTrain</code>. Un Sedán no es “más” que una furgoneta. → <strong>one-hot</strong></p>
</div>
<div class="tarjeta">
<p><strong>Ordinal</strong> Con orden real. La pureza de un diamante, un nivel educativo, una talla S/M/L. → <strong>ordinal encoding con el orden declarado a mano</strong></p>
</div>
<div class="tarjeta">
<p><strong>Binaria</strong> Dos valores. <code>Origin</code>, <code>Man.trans.avail</code>. → <strong>0 y 1, una sola columna</strong></p>
</div>
</div>
<p>La decisión no la toma el código: la toma quien conoce el dominio.</p>
</section>
<section class="slide level2">
<h2>Cuánta variedad hay en cada una</h2>
<div class="sourceCode" id="cb22"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb22-1"><a href=""></a>X_train.select_dtypes(exclude<span class="op">=</span><span class="st">"number"</span>).nunique().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>Manufacturer       31
Type                6
Cylinders           6
DriveTrain          3
AirBags             2
Man.trans.avail     2
Origin              2</pre>
</div>
<div class="alerta">
<p><code>Manufacturer</code> tiene <strong>31 niveles distintos en 74 filas de entrenamiento</strong>. Guarden ese dato: dentro de un rato va a hacer explotar el modelo.</p>
</div>
</section>
<section class="slide level2">
<h2>Binaria: lo más simple que funciona</h2>
<div class="sourceCode" id="cb23"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb23-1"><a href=""></a>es_usa <span class="op">=</span> (X_train[<span class="st">"Origin"</span>] <span class="op">==</span> <span class="st">"USA"</span>).astype(<span class="bu">int</span>)</span>
<span id="cb23-2"><a href=""></a>es_usa.value_counts()</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>Origin
1    39
0    35</pre>
</div>
<p>Con dos categorías, una sola columna 0/1 basta y sobra. Crear dos columnas sería redundante: la segunda sería siempre <code>1 - primera</code>.</p>
</section>
<section class="slide level2">
<h2>Label encoding: ¿para qué sirve?</h2>
<div class="concepto">
<p><strong>Label encoding</strong> sustituye cada categoría por un número entero. Ni más ni menos. <code>LabelEncoder</code> los asigna <strong>por orden alfabético</strong>, empezando en 0.</p>
</div>
<p>Su uso legítimo es <strong>la variable objetivo de un problema de clasificación</strong>: cuando hay que predecir <code>"perro"</code> / <code>"gato"</code> / <code>"pájaro"</code>, el modelo necesita que esas tres etiquetas sean 0, 1 y 2, y ahí el número es solo un identificador que nunca se opera.</p>
<p>El problema empieza cuando alguien lo usa en las <strong>variables de entrada</strong>.</p>
</section>
<section class="slide level2">
<h2>Qué hace exactamente</h2>
<div class="sourceCode" id="cb24"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb24-1"><a href=""></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> LabelEncoder</span>
<span id="cb24-2"><a href=""></a></span>
<span id="cb24-3"><a href=""></a>le <span class="op">=</span> LabelEncoder()</span>
<span id="cb24-4"><a href=""></a>cilindros <span class="op">=</span> cars[<span class="st">"Cylinders"</span>].astype(<span class="bu">str</span>)</span>
<span id="cb24-5"><a href=""></a>codigos <span class="op">=</span> le.fit_transform(cilindros)</span>
<span id="cb24-6"><a href=""></a></span>
<span id="cb24-7"><a href=""></a><span class="co"># la correspondencia que aprendió</span></span>
<span id="cb24-8"><a href=""></a>pd.DataFrame({<span class="st">"categoría"</span>: le.classes_,</span>
<span id="cb24-9"><a href=""></a>              <span class="st">"número asignado"</span>: <span class="bu">range</span>(<span class="bu">len</span>(le.classes_))})</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>  categoría  número asignado
0         3                0
1         4                1
2         5                2
3         6                3
4         8                4
5    rotary                5</pre>
</div>
<p>Ordenó las seis categorías alfabéticamente y les puso 0, 1, 2, 3, 4 y 5.</p>
</section>
<section class="slide level2">
<h2>Y así queda cada fila</h2>
<div class="sourceCode" id="cb25"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb25-1"><a href=""></a>pd.DataFrame({<span class="st">"Cylinders"</span>: cilindros, <span class="st">"codificado"</span>: codigos}).head(<span class="dv">6</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>  Cylinders  codificado
0         4           1
1         6           3
2         6           3
3         6           3
4         4           1
5         4           1</pre>
</div>
<p>Un coche de 4 cilindros pasa a ser un 1, y uno de 6 pasa a ser un 3.</p>
</section>
<section class="slide level2">
<h2>Por qué casi siempre está mal</h2>
<div class="alerta">
<p>El modelo lee esos números como <strong>cantidades</strong>, no como etiquetas. Con esta codificación estamos afirmando tres cosas falsas:</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>rotary</code> &gt; 8 cilindros</strong> Al motor rotativo le tocó el 5 y al de 8 cilindros el 4. Alfabéticamente tiene sentido; mecánicamente no significa nada.</p>
</div>
<div class="tarjeta">
<p><strong>Las distancias son iguales</strong> De 3 a 4 cilindros hay “1”, y de 6 a 8 también hay “1”. En la realidad no.</p>
</div>
<div class="tarjeta">
<p><strong>El orden es el alfabético</strong> Que es una casualidad de cómo se escriben las palabras.</p>
</div>
</div>
<p>Excepción: los <strong>árboles</strong> lo toleran bastante bien, porque parten por umbrales y no interpretan la magnitud.</p>
</section>
<section class="slide level2">
<h2>One-hot: la alternativa para nominales</h2>
<div class="concepto">
<p><strong>One-hot encoding</strong> crea una columna por categoría, con un 1 en la que corresponde y 0 en las demás. Así ninguna categoría queda “por encima” de otra: todas están a la misma distancia.</p>
</div>
<div class="sourceCode" id="cb26"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb26-1"><a href=""></a>pd.get_dummies(X_train[[<span class="st">"Type"</span>]], prefix<span class="op">=</span><span class="st">"Type"</span>, dtype<span class="op">=</span><span class="bu">int</span>).head()</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>    Type_Compact  Type_Large  Type_Midsize  Type_Small  Type_Sporty  Type_Van
65             0           0             0           0            0         1
15             0           0             0           0            0         1
68             0           0             1           0            0         0
78             0           0             0           1            0         0
30             0           0             0           1            0         0</pre>
</div>
</section>
<section class="slide level2">
<h2><code>get_dummies</code> está bien para explorar, no para producción</h2>
<div class="alerta">
<p>Si el conjunto de prueba trae una categoría que el entrenamiento no tenía, <code>get_dummies</code> genera <strong>un juego de columnas distinto</strong> y el modelo recibe una matriz que no reconoce.</p>
</div>
<div class="sourceCode" id="cb27"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb27-1"><a href=""></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> OneHotEncoder</span>
<span id="cb27-2"><a href=""></a></span>
<span id="cb27-3"><a href=""></a>enc <span class="op">=</span> OneHotEncoder(handle_unknown<span class="op">=</span><span class="st">"ignore"</span>, sparse_output<span class="op">=</span><span class="va">False</span>, drop<span class="op">=</span><span class="st">"first"</span>)</span>
<span id="cb27-4"><a href=""></a>enc.fit(X_train[[<span class="st">"Type"</span>, <span class="st">"DriveTrain"</span>]])</span>
<span id="cb27-5"><a href=""></a>enc.get_feature_names_out()</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>array(['Type_Large', 'Type_Midsize', 'Type_Small', 'Type_Sporty',
       'Type_Van', 'DriveTrain_Front', 'DriveTrain_Rear'], dtype=object)</pre>
</div>
<p><code>OneHotEncoder</code> <strong>recuerda</strong> las categorías del entrenamiento y siempre devuelve las mismas columnas, en el mismo orden.</p>
</section>
<section class="slide level2">
<h2>Los dos argumentos que importan</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>handle_unknown="ignore"</code></strong> Una categoría no vista en entrenamiento sale como una fila de ceros, en vez de lanzar una excepción en mitad de producción.</p>
</div>
<div class="tarjeta">
<p><strong><code>drop="first"</code></strong> Quita una columna por variable. Evita la colinealidad perfecta que deja indeterminados los coeficientes de la regresión lineal.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Por qué <code>drop="first"</code></h2>
<div class="concepto">
<p>Con las seis columnas de <code>Type</code>, la suma de todas es siempre 1. Esa <strong>colinealidad perfecta</strong> hace que existan infinitas combinaciones de coeficientes que dan el mismo resultado, y la regresión no sabe cuál elegir.</p>
</div>
<p>Al quitar <code>Compact</code>, esa pasa a ser la categoría de referencia y los demás coeficientes se leen como <em>“cuánto más caro que un Compact”</em>, que además es más fácil de explicar.</p>
<div class="destacado">
<p>Con árboles o con regularización (Ridge, Lasso) no hace falta quitarla, y a veces conviene no hacerlo. Con regresión lineal pura, sí.</p>
</div>
</section>
<section class="slide level2">
<h2>Alta cardinalidad: el problema de <code>Manufacturer</code></h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb28-1"><a href=""></a>vc <span class="op">=</span> X_train[<span class="st">"Manufacturer"</span>].value_counts()</span>
<span id="cb28-2"><a href=""></a><span class="bu">print</span>(vc.head(<span class="dv">6</span>))</span>
<span id="cb28-3"><a href=""></a><span class="bu">print</span>(<span class="st">"marcas con 1 solo coche:"</span>, (vc <span class="op">==</span> <span class="dv">1</span>).<span class="bu">sum</span>(), <span class="st">"de"</span>, <span class="bu">len</span>(vc))</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>Manufacturer
Ford         7
Chevrolet    6
Nissan       4
Dodge        4
Pontiac      4
Buick        4
Name: count, dtype: int64
marcas con 1 solo coche: 12 de 31</pre>
</div>
<p>One-hot sobre esto son <strong>31 columnas nuevas</strong>, 12 de ellas con un único 1. De una columna así no se aprende nada: se memoriza esa fila.</p>
</section>
<section class="slide level2">
<h2>Salida 1 · Agrupar las categorías raras</h2>
<p><strong>Cuándo:</strong> siempre que haya una cola larga de categorías poco frecuentes y no exista un criterio de dominio mejor. Es la primera que hay que probar.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb29-1"><a href=""></a>frecuentes <span class="op">=</span> vc[vc <span class="op">&gt;=</span> <span class="dv">3</span>].index</span>
<span id="cb29-2"><a href=""></a>X_train[<span class="st">"Manufacturer"</span>] <span class="op">=</span> X_train[<span class="st">"Manufacturer"</span>].where(</span>
<span id="cb29-3"><a href=""></a>    X_train[<span class="st">"Manufacturer"</span>].isin(frecuentes), <span class="st">"Otras"</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>Manufacturer
Otras         26
Ford           7
Chevrolet      6
Nissan         4
Buick          4
Mazda          4
Dodge          4
Pontiac        4
Oldsmobile     3
Subaru         3
Hyundai        3
Volkswagen     3
Toyota         3
Name: count, dtype: int64</pre>
</div>
<p>De 31 niveles a 13. <code>OneHotEncoder(min_frequency=3)</code> lo hace solo.</p>
</section>
<section class="slide level2">
<h2>Salida 2 · Frequency encoding</h2>
<div class="concepto">
<p>Sustituir cada categoría por <strong>la frecuencia con que aparece</strong>. Una sola columna numérica, sin importar cuántos niveles haya.</p>
</div>
<div class="sourceCode" id="cb30"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb30-1"><a href=""></a>frec <span class="op">=</span> cars[<span class="st">"Manufacturer"</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb30-2"><a href=""></a>cars[<span class="st">"Manuf_frec"</span>] <span class="op">=</span> cars[<span class="st">"Manufacturer"</span>].<span class="bu">map</span>(frec)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>0    0.0215
1    0.0215
2    0.0215
3    0.0215
4    0.0108
5    0.0430</pre>
</div>
<p><strong>Cuándo:</strong> cuando la popularidad de la categoría es en sí misma informativa —un fabricante con muchos modelos es un fabricante masivo— y hay miles de niveles. <strong>Riesgo:</strong> dos marcas distintas con la misma frecuencia quedan indistinguibles.</p>
</section>
<section class="slide level2">
<h2>Salida 3 · Target encoding</h2>
<div class="concepto">
<p>Sustituir cada categoría por <strong>la media de la variable objetivo</strong> dentro de esa categoría. Una columna, y muy informativa: le da al modelo directamente lo que la categoría dice sobre el precio.</p>
</div>
<div class="sourceCode" id="cb31"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb31-1"><a href=""></a>medias <span class="op">=</span> cars.groupby(<span class="st">"Manufacturer"</span>)[<span class="st">"Price"</span>].mean()</span>
<span id="cb31-2"><a href=""></a>cars[<span class="st">"Manuf_te"</span>] <span class="op">=</span> cars[<span class="st">"Manufacturer"</span>].<span class="bu">map</span>(medias)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>0    24.90
1    24.90
2    33.40
3    33.40
4    30.00
5    21.62</pre>
</div>
<p><strong>Cuándo:</strong> competiciones y modelos tabulares con cardinalidad muy alta (códigos postales, IDs de producto). Suele ser la codificación que más aporta.</p>
</section>
<section class="slide level2">
<h2>Target encoding: el peligro</h2>
<div class="terminal" data-nocopy="">
<pre>Infiniti: media = 47.9  (calculada con 1 coche)</pre>
</div>
<div class="alerta">
<p>Para una marca con un solo coche, la “media de la categoría” <strong>es el precio de ese coche</strong>. Le estamos dando al modelo la respuesta de esa fila disfrazada de variable de entrada. Es fuga de datos de manual.</p>
</div>
<p>Se controla con <strong>suavizado</strong> (mezclar la media del grupo con la media global, según cuántas filas tenga) y calculando las medias <strong>dentro de una validación cruzada</strong>. <code>sklearn.preprocessing.TargetEncoder</code> ya lo trae hecho.</p>
</section>
<section class="slide level2">
<h2>Salida 4 · Agrupar por conocimiento del dominio</h2>
<div class="concepto">
<p>Reemplazar la categoría por una <strong>propiedad suya</strong> que sí tenga pocos niveles y significado.</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Marca → origen</strong> <code>Manufacturer</code> (31) → <code>Origin</code> (2). Ya lo tenemos en el dataset.</p>
</div>
<div class="tarjeta">
<p><strong>Marca → gama</strong> Generalista / prémium / lujo. 31 → 3.</p>
</div>
<div class="tarjeta">
<p><strong>Marca → grupo empresarial</strong> Audi, SEAT y Volkswagen comparten plataformas. 31 → ~10.</p>
</div>
</div>
<p><strong>Cuándo:</strong> siempre que se pueda. Es la única salida que <strong>añade información</strong> en lugar de limitarse a comprimir la que ya había, y la que mejor resiste categorías nuevas en producción.</p>
</section>
<section class="slide level2">
<h2>Salida 5 · Embeddings</h2>
<div class="concepto">
<p>Aprender, durante el entrenamiento de una red neuronal, un <strong>vector de pocas dimensiones</strong> para cada categoría. Categorías que se comportan parecido acaban con vectores parecidos.</p>
</div>
<p>Es lo mismo que se hace con las palabras en procesamiento de lenguaje: 50.000 palabras representadas en 300 números.</p>
<p><strong>Cuándo:</strong> cardinalidades de miles o decenas de miles (usuarios, productos, ciudades) y con una red neuronal de por medio. <strong>Cuándo no:</strong> en este curso. Con 31 marcas y 93 coches, un embedding es artillería para matar una mosca.</p>
</section>
<section class="slide level2">
<h2>Ordinales de verdad: <code>diamonds</code></h2>
<div class="sourceCode" id="cb32"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb32-1"><a href=""></a><span class="cf">for</span> c <span class="kw">in</span> [<span class="st">"cut"</span>, <span class="st">"color"</span>, <span class="st">"clarity"</span>]:</span>
<span id="cb32-2"><a href=""></a>    <span class="bu">print</span>(c, dia[c].nunique(), <span class="bu">sorted</span>(dia[c].unique()))</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>cut 5 ['Fair', 'Good', 'Ideal', 'Premium', 'Very Good']
color 7 ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity 8 ['I1', 'IF', 'SI1', 'SI2', 'VS1', 'VS2', 'VVS1', 'VVS2']</pre>
</div>
<div class="alerta">
<p>Ese es el orden <strong>alfabético</strong>, y no tiene nada que ver con la calidad. En color, <code>D</code> es el mejor y <code>J</code> el peor. Si dejamos que la máquina ordene, el orden sale justo al revés.</p>
</div>
</section>
<section class="slide level2">
<h2><code>OrdinalEncoder</code> con el orden declarado</h2>
<div class="sourceCode" id="cb33"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb33-1"><a href=""></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> OrdinalEncoder</span>
<span id="cb33-2"><a href=""></a></span>
<span id="cb33-3"><a href=""></a>cut     <span class="op">=</span> [<span class="st">"Fair"</span>, <span class="st">"Good"</span>, <span class="st">"Very Good"</span>, <span class="st">"Premium"</span>, <span class="st">"Ideal"</span>]</span>
<span id="cb33-4"><a href=""></a>color   <span class="op">=</span> [<span class="st">"J"</span>, <span class="st">"I"</span>, <span class="st">"H"</span>, <span class="st">"G"</span>, <span class="st">"F"</span>, <span class="st">"E"</span>, <span class="st">"D"</span>]</span>
<span id="cb33-5"><a href=""></a>clarity <span class="op">=</span> [<span class="st">"I1"</span>, <span class="st">"SI2"</span>, <span class="st">"SI1"</span>, <span class="st">"VS2"</span>, <span class="st">"VS1"</span>, <span class="st">"VVS2"</span>, <span class="st">"VVS1"</span>, <span class="st">"IF"</span>]</span>
<span id="cb33-6"><a href=""></a></span>
<span id="cb33-7"><a href=""></a>oe <span class="op">=</span> OrdinalEncoder(categories<span class="op">=</span>[cut, color, clarity])</span>
<span id="cb33-8"><a href=""></a>oe.fit_transform(dia[[<span class="st">"cut"</span>, <span class="st">"color"</span>, <span class="st">"clarity"</span>]])</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>array([[4., 5., 1.],
       [3., 5., 2.],
       [1., 5., 4.],
       ...,
       [2., 6., 2.],
       [3., 2., 1.],
       [4., 6., 1.]], shape=(53940, 3))</pre>
</div>
<p>De peor a mejor. Ese orden lo pone quien sabe de diamantes, no el código.</p>
</section>
<section class="slide level2">
<h2>¿Ordinal u one-hot? El coste</h2>
<div class="terminal" data-nocopy="">
<pre>one-hot de cut+color+clarity : 20 columnas
ordinal de cut+color+clarity :  3 columnas</pre>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Ordinal gana cuando</strong> El orden es real y el efecto es más o menos monótono. Ahorra 17 columnas.</p>
</div>
<div class="tarjeta">
<p><strong>One-hot gana cuando</strong> No hay orden, o el efecto no es monótono: que la categoría del medio sea la más cara, por ejemplo.</p>
</div>
</div>
<p>En la duda, y con datos suficientes, one-hot es la apuesta segura: no impone ninguna estructura que no esté en los datos.</p>
</section>
<section class="slide level2">
<h2>Chequeo 5 · Con las categóricas codificadas</h2>
<p>Ya podemos meter las 7 columnas de texto. One-hot a todas, sin más.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb34-1"><a href=""></a><span class="im">from</span> sklearn.compose <span class="im">import</span> ColumnTransformer</span>
<span id="cb34-2"><a href=""></a></span>
<span id="cb34-3"><a href=""></a><span class="kw">def</span> rama_categorica(min_frec):</span>
<span id="cb34-4"><a href=""></a>    <span class="cf">return</span> Pipeline([(<span class="st">"imp"</span>, SimpleImputer(strategy<span class="op">=</span><span class="st">"constant"</span>,</span>
<span id="cb34-5"><a href=""></a>                                           fill_value<span class="op">=</span><span class="st">"Desconocido"</span>)),</span>
<span id="cb34-6"><a href=""></a>                     (<span class="st">"oh"</span>,  OneHotEncoder(handle_unknown<span class="op">=</span><span class="st">"ignore"</span>,</span>
<span id="cb34-7"><a href=""></a>                                           drop<span class="op">=</span><span class="st">"first"</span>,</span>
<span id="cb34-8"><a href=""></a>                                           min_frequency<span class="op">=</span>min_frec))])</span>
<span id="cb34-9"><a href=""></a></span>
<span id="cb34-10"><a href=""></a>pre_todas <span class="op">=</span> ColumnTransformer([</span>
<span id="cb34-11"><a href=""></a>    (<span class="st">"num"</span>, Pipeline([(<span class="st">"imp"</span>, SimpleImputer(strategy<span class="op">=</span><span class="st">"median"</span>))]), num_cols),</span>
<span id="cb34-12"><a href=""></a>    (<span class="st">"cat"</span>, rama_categorica(<span class="dv">1</span>), cat_cols),</span>
<span id="cb34-13"><a href=""></a>])</span>
<span id="cb34-14"><a href=""></a><span class="bu">print</span>(<span class="st">"columnas tras codificar:"</span>, pre_todas.fit(X).transform(X).shape[<span class="dv">1</span>])</span>
<span id="cb34-15"><a href=""></a></span>
<span id="cb34-16"><a href=""></a>chequeo(<span class="st">"5 · + one-hot de todas"</span>,</span>
<span id="cb34-17"><a href=""></a>        <span class="kw">lambda</span> m: Pipeline([(<span class="st">"pre"</span>, pre_todas), (<span class="st">"reg"</span>, m)]), X, y)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>columnas tras codificar: 62   (para 93 coches)

capítulo                    MSE lineal  R2 lineal    MSE red    R2 red
4 · SimpleImputer(mediana)       37.39      0.440   71652.37 -1132.739
5 · + one-hot de todas           <span class="salida">91.10     -0.242</span>   18748.45  -389.281</pre>
</div>
</section>
<section class="slide level2">
<h2>El <span class="math inline">\(R^2\)</span> se volvió negativo</h2>
<div class="alerta">
<p>De 0,440 a <strong>−0,242</strong>: añadir información hizo el modelo <strong>peor que predecir siempre la media</strong>. Y no es ruido, es aritmética: 62 columnas para 93 coches.</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>El culpable tiene nombre</strong> <code>Manufacturer</code>, con sus 31 niveles, aporta 30 de esas 62 columnas.</p>
</div>
<div class="tarjeta">
<p><strong>La red “mejora”</strong> De −1132 a −389. Sigue siendo un disparate; que baje no significa que sirva.</p>
</div>
</div>
<p>La codificación no estaba mal. Lo que falta es <strong>controlar la cardinalidad</strong>, que es el capítulo siguiente.</p>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>6 · Agrupación y discretización</h1>
<p><code>groupby</code> no es solo para informes</p>
</section>
<section class="slide level2">
<h2><code>groupby</code> para entender antes de transformar</h2>
<div class="sourceCode" id="cb35"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb35-1"><a href=""></a>(cars.groupby(<span class="st">"Type"</span>)</span>
<span id="cb35-2"><a href=""></a>     .agg(n<span class="op">=</span>(<span class="st">"Price"</span>, <span class="st">"size"</span>),</span>
<span id="cb35-3"><a href=""></a>          precio_medio<span class="op">=</span>(<span class="st">"Price"</span>, <span class="st">"mean"</span>),</span>
<span id="cb35-4"><a href=""></a>          cv_medio<span class="op">=</span>(<span class="st">"MPG.city"</span>, <span class="st">"mean"</span>),</span>
<span id="cb35-5"><a href=""></a>          hp_medio<span class="op">=</span>(<span class="st">"Horsepower"</span>, <span class="st">"mean"</span>))</span>
<span id="cb35-6"><a href=""></a>     .<span class="bu">round</span>(<span class="dv">1</span>).sort_values(<span class="st">"precio_medio"</span>, ascending<span class="op">=</span><span class="va">False</span>))</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>          n  precio_medio  cv_medio  hp_medio
Type                                         
Midsize  22          27.2      19.5     173.1
Large    11          24.3      18.4     179.5
Sporty   14          19.4      21.8     160.1
Van       9          19.1      17.0     149.4
Compact  16          18.2      22.7     131.0
Small    21          10.2      29.9      91.0</pre>
</div>
<p><code>Type</code> separa muy bien el precio: de 10,2 a 27,2. Es una variable que vale la pena conservar.</p>
</section>
<section class="slide level2">
<h2>Discretizar: de continua a categórica</h2>
<div class="sourceCode" id="cb36"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb36-1"><a href=""></a>cars[<span class="st">"gama"</span>] <span class="op">=</span> pd.cut(cars[<span class="st">"Price"</span>],</span>
<span id="cb36-2"><a href=""></a>                      bins<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">12</span>, <span class="dv">20</span>, <span class="dv">100</span>],</span>
<span id="cb36-3"><a href=""></a>                      labels<span class="op">=</span>[<span class="st">"económico"</span>, <span class="st">"medio"</span>, <span class="st">"alto"</span>])</span>
<span id="cb36-4"><a href=""></a>cars[<span class="st">"gama"</span>].value_counts().sort_index()</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>gama
económico    22
medio        40
alto         31</pre>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>pd.cut</code></strong> Cortes que ustedes eligen. Úsenlo cuando los umbrales significan algo.</p>
</div>
<div class="tarjeta">
<p><strong><code>pd.qcut</code></strong> Cortes por cuantiles: grupos del mismo tamaño.</p>
</div>
<div class="tarjeta">
<p><strong><code>KBinsDiscretizer</code></strong> La versión de sklearn, encajable en un <code>Pipeline</code>.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Cuidado con discretizar</h2>
<div class="alerta">
<p>Discretizar <strong>tira información</strong>: dos coches de 11.900 y 12.100 acaban en gamas distintas, y uno de 12.100 y otro de 19.900 acaban en la misma.</p>
</div>
<p>Se justifica cuando la relación no es lineal y el modelo sí lo es, cuando los cortes tienen sentido de negocio, o cuando hay que comunicar el resultado a alguien que no va a leer un coeficiente.</p>
<p>No se justifica “para simplificar”: los modelos no necesitan que les simplifiquen las variables continuas.</p>
</section>
<section class="slide level2">
<h2>Chequeo 6 · Agrupando las categorías raras</h2>
<p>Una categoría necesita <strong>15 coches</strong> para tener columna propia. Las demás se juntan en un grupo.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb37-1"><a href=""></a>pre_agrupadas <span class="op">=</span> ColumnTransformer([</span>
<span id="cb37-2"><a href=""></a>    (<span class="st">"num"</span>, Pipeline([(<span class="st">"imp"</span>, SimpleImputer(strategy<span class="op">=</span><span class="st">"median"</span>))]), num_cols),</span>
<span id="cb37-3"><a href=""></a>    (<span class="st">"cat"</span>, rama_categorica(<span class="dv">15</span>), cat_cols),          <span class="co"># &lt;- el cambio</span></span>
<span id="cb37-4"><a href=""></a>])</span>
<span id="cb37-5"><a href=""></a><span class="bu">print</span>(<span class="st">"columnas:"</span>, pre_todas.fit(X).transform(X).shape[<span class="dv">1</span>], <span class="st">"-&gt;"</span>,</span>
<span id="cb37-6"><a href=""></a>      pre_agrupadas.fit(X).transform(X).shape[<span class="dv">1</span>])</span>
<span id="cb37-7"><a href=""></a></span>
<span id="cb37-8"><a href=""></a>chequeo(<span class="st">"6 · + agrupar categorías raras"</span>,</span>
<span id="cb37-9"><a href=""></a>        <span class="kw">lambda</span> m: Pipeline([(<span class="st">"pre"</span>, pre_agrupadas), (<span class="st">"reg"</span>, m)]), X, y)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>columnas: 62 -&gt; 26

capítulo                       MSE lineal  R2 lineal    MSE red    R2 red
4 · SimpleImputer(mediana)          37.39      0.440   71652.37 -1132.739
5 · + one-hot de todas              91.10     -0.242   18748.45  -389.281
6 · + agrupar categorías raras      <span class="salida">33.30      0.455</span>   26326.33  -377.586</pre>
</div>
</section>
<section class="slide level2">
<h2>Recuperado, y mejor que antes</h2>
<div class="concepto">
<p>El <span class="math inline">\(R^2\)</span> pasa de −0,242 a <strong>0,455</strong>: no solo deshacemos el destrozo del capítulo anterior, sino que superamos el 0,440 que teníamos sin categóricas. Ahora sí aportan.</p>
</div>
<div class="destacado">
<p>La lección no es “one-hot es peligroso”. Es que <strong>una técnica correcta, aplicada sin mirar lo que produce, hace daño</strong>. Bastó contar cuántos coches había por marca.</p>
</div>
<p>Seis capítulos y la red sigue en −377.</p>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>7 · Escalado</h1>
<p>Poner todas las variables en la misma unidad</p>
</section>
<section class="slide level2">
<h2>Por qué escalar</h2>
<div class="terminal" data-nocopy="">
<pre>      Horsepower  MPG.city   Weight
mean      141.20     22.24  3093.11
std        48.03      5.70   592.10
min        55.00     15.00  1695.00
max       300.00     46.00  4105.00</pre>
</div>
<div class="concepto">
<p>Cualquier algoritmo basado en <strong>distancias</strong> (KNN, k-means, SVM) o en <strong>descenso de gradiente</strong> verá que <code>Weight</code> domina, simplemente porque sus números son más grandes. No porque importe más.</p>
</div>
</section>
<section class="slide level2">
<h2>Y se mide</h2>
<div class="sourceCode" id="cb38"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb38-1"><a href=""></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> KNeighborsRegressor</span>
<span id="cb38-2"><a href=""></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb38-3"><a href=""></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_absolute_error</span>
<span id="cb38-4"><a href=""></a></span>
<span id="cb38-5"><a href=""></a>sin <span class="op">=</span> Pipeline([(<span class="st">"imp"</span>, SimpleImputer()),</span>
<span id="cb38-6"><a href=""></a>                (<span class="st">"knn"</span>, KNeighborsRegressor(<span class="dv">5</span>))]).fit(X_train[num_cols], y_train)</span>
<span id="cb38-7"><a href=""></a></span>
<span id="cb38-8"><a href=""></a>con <span class="op">=</span> Pipeline([(<span class="st">"imp"</span>, SimpleImputer()),</span>
<span id="cb38-9"><a href=""></a>                (<span class="st">"esc"</span>, StandardScaler()),</span>
<span id="cb38-10"><a href=""></a>                (<span class="st">"knn"</span>, KNeighborsRegressor(<span class="dv">5</span>))]).fit(X_train[num_cols], y_train)</span>
<span id="cb38-11"><a href=""></a></span>
<span id="cb38-12"><a href=""></a><span class="cf">for</span> nombre, m <span class="kw">in</span> [(<span class="st">"sin escalar"</span>, sin), (<span class="st">"escalado   "</span>, con)]:</span>
<span id="cb38-13"><a href=""></a>    p <span class="op">=</span> m.predict(X_test[num_cols])</span>
<span id="cb38-14"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"KNN </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss"> : MAE </span><span class="sc">{</span>mean_absolute_error(y_test, p)<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>KNN sin escalar : MAE 4.39
KNN escalado    : MAE 3.29</pre>
</div>
<p>Un 10 % mejor sin tocar el modelo. Con variables de escalas más dispares la diferencia es mucho mayor.</p>
</section>
<section class="slide level2">
<h2>Estandarización · <code>StandardScaler</code></h2>
<p>Resta la media y divide por la desviación: media 0, desviación 1.</p>
<p><span class="math display">\[z = \frac{x - \mu}{\sigma}\]</span></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb39-1"><a href=""></a>cols <span class="op">=</span> [<span class="st">"Horsepower"</span>, <span class="st">"MPG.city"</span>, <span class="st">"Weight"</span>]</span>
<span id="cb39-2"><a href=""></a></span>
<span id="cb39-3"><a href=""></a>std <span class="op">=</span> StandardScaler().fit(X_train[cols])</span>
<span id="cb39-4"><a href=""></a>pd.DataFrame(std.transform(X_train[cols]), columns<span class="op">=</span>cols) <span class="op">\</span></span>
<span id="cb39-5"><a href=""></a>  .describe().loc[[<span class="st">"mean"</span>, <span class="st">"std"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>]].<span class="bu">round</span>(<span class="dv">2</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>      Horsepower  MPG.city  Weight
mean       -0.00      0.00    0.00
std         1.01      1.01    1.01
min        -1.81     -1.28   -2.38
max         3.33      4.20    1.72</pre>
</div>
<p>No acota el rango: los atípicos siguen lejos (ese 4,20 es un coche de 46 mpg).</p>
</section>
<section class="slide level2">
<h2>Normalización · <code>MinMaxScaler</code></h2>
<p>Lleva el mínimo a 0 y el máximo a 1.</p>
<p><span class="math display">\[x' = \frac{x - x_{\min}}{x_{\max} - x_{\min}}\]</span></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb40-1"><a href=""></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> MinMaxScaler</span>
<span id="cb40-2"><a href=""></a></span>
<span id="cb40-3"><a href=""></a>mm <span class="op">=</span> MinMaxScaler().fit(X_train[cols])</span>
<span id="cb40-4"><a href=""></a>pd.DataFrame(mm.transform(X_train[cols]), columns<span class="op">=</span>cols) <span class="op">\</span></span>
<span id="cb40-5"><a href=""></a>  .describe().loc[[<span class="st">"mean"</span>, <span class="st">"std"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>]].<span class="bu">round</span>(<span class="dv">2</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>      Horsepower  MPG.city  Weight
mean        0.35      0.23    0.58
std         0.20      0.18    0.25
min         0.00      0.00    0.00
max         1.00      1.00    1.00</pre>
</div>
<p>Rango garantizado, pero <strong>un solo atípico comprime a todos los demás</strong>: miren la media de <code>MPG.city</code>, aplastada en 0,23.</p>
</section>
<section class="slide level2">
<h2>Escalado robusto · <code>RobustScaler</code></h2>
<p>Usa la mediana y el rango intercuartílico en vez de media y desviación.</p>
<p><span class="math display">\[x' = \frac{x - \text{mediana}}{Q_3 - Q_1}\]</span></p>
<div class="terminal" data-nocopy="">
<pre>      Horsepower  MPG.city  Weight
mean        0.02      0.25    0.03
std         0.75      1.14    0.68
min        -1.33     -1.20   -1.57
max         2.50      5.00    1.19</pre>
</div>
<div class="destacado">
<p>El centro queda en 0 y el grueso de los datos entre −1 y 1, <strong>sin que los atípicos muevan la referencia</strong>. Es la opción por defecto cuando hay valores extremos que no queremos eliminar.</p>
</div>
</section>
<section class="slide level2">
<h2>Cuál usar</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>StandardScaler</code></strong> El defecto razonable. Regresión lineal, regularizadas, SVM, redes, PCA.</p>
</div>
<div class="tarjeta">
<p><strong><code>MinMaxScaler</code></strong> Cuando hace falta un rango acotado y no hay atípicos. Imágenes, redes con sigmoide.</p>
</div>
<div class="tarjeta">
<p><strong><code>RobustScaler</code></strong> Cuando hay atípicos de verdad y no se pueden quitar.</p>
</div>
<div class="tarjeta">
<p><strong>Ninguno</strong> Árboles, bosques aleatorios, <em>gradient boosting</em>. Les da exactamente igual.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Lo que el escalador aprendió</h2>
<div class="sourceCode" id="cb41"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb41-1"><a href=""></a><span class="bu">print</span>(<span class="st">"media aprendida en train :"</span>, std.mean_.<span class="bu">round</span>(<span class="dv">2</span>))</span>
<span id="cb41-2"><a href=""></a><span class="bu">print</span>(<span class="st">"desviación aprendida     :"</span>, std.scale_.<span class="bu">round</span>(<span class="dv">2</span>))</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>media aprendida en train : [ 141.2    22.24 3093.11]
desviación aprendida     : [ 47.7    5.66 588.08]</pre>
</div>
<div class="concepto">
<p>Esos seis números <strong>son el modelo de preprocesamiento</strong>. Hay que guardarlos y llevárselos a producción junto con el modelo. Si se pierden, las predicciones futuras no significan nada.</p>
</div>
</section>
<section class="slide level2">
<h2>El test no queda entre 0 y 1, y está bien</h2>
<div class="sourceCode" id="cb42"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb42-1"><a href=""></a>pd.DataFrame(mm.transform(X_test[cols]),</span>
<span id="cb42-2"><a href=""></a>             columns<span class="op">=</span>cols).describe().loc[[<span class="st">"min"</span>, <span class="st">"max"</span>]].<span class="bu">round</span>(<span class="dv">2</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>     Horsepower  MPG.city  Weight
min        0.08      0.00    0.15
max        1.00      0.55    0.93</pre>
</div>
<div class="destacado">
<p>El máximo de <code>MPG.city</code> en test es 0,55 porque el coche más eficiente estaba en entrenamiento. Si un dato de test superara el máximo de train, saldría <strong>mayor que 1</strong>. No es un error: es la prueba de que no hubo fuga.</p>
</div>
</section>
<section class="slide level2">
<h2>Chequeo 7 · Con escalado</h2>
<p>Una línea más en la rama numérica: <code>StandardScaler()</code>.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb43-1"><a href=""></a>pre_escalado <span class="op">=</span> ColumnTransformer([</span>
<span id="cb43-2"><a href=""></a>    (<span class="st">"num"</span>, Pipeline([(<span class="st">"imp"</span>, SimpleImputer(strategy<span class="op">=</span><span class="st">"median"</span>)),</span>
<span id="cb43-3"><a href=""></a>                      (<span class="st">"esc"</span>, StandardScaler())]), num_cols),</span>
<span id="cb43-4"><a href=""></a>    (<span class="st">"cat"</span>, rama_categorica(<span class="dv">15</span>), cat_cols),</span>
<span id="cb43-5"><a href=""></a>])</span>
<span id="cb43-6"><a href=""></a></span>
<span id="cb43-7"><a href=""></a>chequeo(<span class="st">"7 · + escalado"</span>,</span>
<span id="cb43-8"><a href=""></a>        <span class="kw">lambda</span> m: Pipeline([(<span class="st">"pre"</span>, pre_escalado), (<span class="st">"reg"</span>, m)]), X, y)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>capítulo                       MSE lineal  R2 lineal    MSE red    R2 red
5 · + one-hot de todas              91.10     -0.242   18748.45  -389.281
6 · + agrupar categorías raras      33.30      0.455   26326.33  -377.586
7 · + StandardScaler                33.30      0.455      <span class="salida">35.23     0.449</span></pre>
</div>
</section>
<section class="slide level2">
<h2>Esta es la diapositiva de la sesión</h2>
<div class="concepto">
<p>La red pasa de <span class="math inline">\(R^2 = -377{,}6\)</span> a <span class="math inline">\(R^2 = +0{,}449\)</span>. El MSE cae de <strong>26.326 a 35</strong>: es setecientas veces menos error. La regresión lineal, en la misma línea, no se mueve <strong>ni una milésima</strong>.</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Por qué a la lineal le da igual</strong> Resuelve un sistema de ecuaciones. Si una columna vale mil veces más, su coeficiente vale mil veces menos y el resultado es idéntico.</p>
</div>
<div class="tarjeta">
<p><strong>Por qué a la red le cambia todo</strong> Entrena a base de pasos pequeños. Con las columnas en escalas incomparables, la dirección de mejora es casi imposible de encontrar. Vamos a verlo por dentro.</p>
</div>
</div>
<div class="alerta">
<p>No existe “el preprocesamiento correcto”. Existe <strong>el correcto para el modelo que van a usar</strong>.</p>
</div>
</section>
<section class="slide level2">
<h2>Abramos la red y miremos</h2>
<div class="sourceCode" id="cb44"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb44-1"><a href=""></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> KFold</span>
<span id="cb44-2"><a href=""></a></span>
<span id="cb44-3"><a href=""></a>Xn <span class="op">=</span> X[num_cols].dropna()<span class="op">;</span> yn <span class="op">=</span> y.loc[Xn.index]</span>
<span id="cb44-4"><a href=""></a>tr, te <span class="op">=</span> <span class="bu">next</span>(<span class="bu">iter</span>(KFold(<span class="dv">5</span>).split(Xn)))</span>
<span id="cb44-5"><a href=""></a></span>
<span id="cb44-6"><a href=""></a><span class="cf">for</span> etiqueta, pasos <span class="kw">in</span> [(<span class="st">"SIN escalar"</span>, []),</span>
<span id="cb44-7"><a href=""></a>                        (<span class="st">"CON escalar"</span>, [(<span class="st">"esc"</span>, StandardScaler())])]:</span>
<span id="cb44-8"><a href=""></a>    m <span class="op">=</span> Pipeline(pasos <span class="op">+</span> [(<span class="st">"red"</span>, MLPRegressor(hidden_layer_sizes<span class="op">=</span>(<span class="dv">32</span>,),</span>
<span id="cb44-9"><a href=""></a>                                               max_iter<span class="op">=</span><span class="dv">2000</span>,</span>
<span id="cb44-10"><a href=""></a>                                               random_state<span class="op">=</span><span class="dv">7</span>))])</span>
<span id="cb44-11"><a href=""></a>    m.fit(Xn.iloc[tr], yn.iloc[tr])</span>
<span id="cb44-12"><a href=""></a>    r, p <span class="op">=</span> m.named_steps[<span class="st">"red"</span>], m.predict(Xn.iloc[te])</span>
<span id="cb44-13"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>etiqueta<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>r<span class="sc">.</span>n_iter_<span class="sc">}</span><span class="ss"> iteraciones, pérdida </span><span class="sc">{</span>r<span class="sc">.</span>loss_<span class="sc">:.3g}</span><span class="ss">, "</span></span>
<span id="cb44-14"><a href=""></a>          <span class="ss">f"peso mayor </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(r.coefs_[<span class="dv">0</span>])<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">, "</span></span>
<span id="cb44-15"><a href=""></a>          <span class="ss">f"predice de </span><span class="sc">{</span>p<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.0f}</span><span class="ss"> a </span><span class="sc">{</span>p<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.0f}</span><span class="ss">"</span>)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>                    SIN escalar        CON escalar
iteraciones usadas       <span class="salida">40 de 2000</span>       2000 de 2000
pérdida final              3.27e+04               2.99
peso mayor                    0.375              1.978
predicciones           <span class="salida">-478 a  212</span>          11 a  41
precios reales             11 a   40          11 a   40</pre>
</div>
</section>
<section class="slide level2">
<h2>No es que explote: es que se rinde</h2>
<div class="alerta">
<p>Lo primero que sorprende: <strong>los pesos no se disparan</strong>. El mayor vale 0,375, más pequeño que el 1,978 de la versión escalada. La red no revienta.</p>
</div>
<div class="concepto">
<p>Lo que pasa es que <strong>se para sola en la iteración 40 de 2000</strong>. La pérdida cae rápido al principio —de 690.000 a 33.000— y ahí se estanca. <code>MLPRegressor</code> deja de entrenar cuando la pérdida no mejora más de <code>tol=1e-4</code> durante 10 rondas seguidas, y eso ocurre enseguida.</p>
</div>
<p>Se detiene creyendo que ha terminado, con una pérdida de 33.000 y prediciendo <strong>precios negativos</strong>: de −478 a 212 mil dólares para coches que cuestan entre 11 y 40.</p>
<div class="destacado">
<p>Y la escalada, en cambio, agota las 2000 iteraciones: <strong>todavía estaba mejorando</strong> cuando se le acabó el permiso.</p>
</div>
</section>
<section class="slide level2">
<h2>De ahí sale el <span class="math inline">\(R^2\)</span> de −377</h2>
<p><span class="math display">\[R^2 = 1 - \frac{SS_{res}}{SS_{tot}}\]</span></p>
<div class="terminal" data-nocopy="">
<pre>SS_res  (error del modelo)     2.102.083
SS_tot  (varianza del precio)      1.343

R2 = 1 - 2.102.083 / 1.343 = -1564</pre>
</div>
<div class="concepto">
<p>El denominador es <strong>pequeño</strong>: los precios se mueven en un rango estrecho, así que hay poca varianza que explicar. El numerador es enorme porque la red falla por cientos de miles. Un cociente de mil y pico da un <span class="math inline">\(R^2\)</span> de mil y pico en negativo.</p>
</div>
<div class="destacado">
<p>Un <span class="math inline">\(R^2\)</span> muy negativo no significa “mil veces peor que la media” en ningún sentido intuitivo. Significa que el error es de <strong>otro orden de magnitud</strong> que la variación que se pretendía explicar.</p>
</div>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>8 · Transformar variables sesgadas</h1>

</section>
<section class="slide level2">
<h2>El precio de los diamantes</h2>
<div class="sourceCode" id="cb45"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb45-1"><a href=""></a><span class="bu">print</span>(<span class="ss">f"asimetría de price      : </span><span class="sc">{</span>dia[<span class="st">'price'</span>]<span class="sc">.</span>skew()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb45-2"><a href=""></a><span class="bu">print</span>(<span class="ss">f"asimetría de log(price) : </span><span class="sc">{</span>np<span class="sc">.</span>log1p(dia[<span class="st">'price'</span>])<span class="sc">.</span>skew()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb45-3"><a href=""></a><span class="bu">print</span>(dia[<span class="st">"price"</span>].describe().<span class="bu">round</span>(<span class="dv">1</span>))</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>asimetría de price      : 1.618
asimetría de log(price) : 0.116
count    53940.0
mean      3932.8
std       3989.4
min        326.0
25%        950.0
50%       2401.0
75%       5324.2
max      18823.0
Name: price, dtype: float64</pre>
</div>
<p>Media 3.933 y mediana 2.401: la media va muy por encima, señal clara de cola a la derecha. El logaritmo la deja casi simétrica.</p>
</section>
<section class="slide level2">
<h2>Por qué molesta el sesgo</h2>
<div class="concepto">
<p>La regresión lineal minimiza el <strong>error al cuadrado</strong>. Con una cola larga, los pocos diamantes carísimos aportan errores enormes al elevarlos al cuadrado, y el ajuste entero se va detrás de ellos para complacerlos.</p>
</div>
<p>Al trabajar en escala logarítmica, un error del 10 % pesa lo mismo en un diamante de 500 dólares que en uno de 15.000. Que suele ser lo que queremos.</p>
</section>
<section class="slide level2">
<h2>Cuándo y cómo transformar</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>np.log1p</code></strong> Para variables positivas con cola derecha: precios, ingresos, poblaciones. El <code>1p</code> es para que aguante los ceros.</p>
</div>
<div class="tarjeta">
<p><strong><code>PowerTransformer</code></strong> Yeo-Johnson busca el exponente que más acerca a la normal. Admite negativos.</p>
</div>
<div class="tarjeta">
<p><strong><code>QuantileTransformer</code></strong> Fuerza la distribución que se le pida. Muy agresivo; puede destruir relaciones reales entre variables.</p>
</div>
</div>
<div class="alerta">
<p>Si transforman la <strong>variable objetivo</strong>, las predicciones salen en escala logarítmica: hay que deshacer con <code>np.expm1</code> antes de interpretar el error.</p>
</div>
</section>
<section class="slide level2">
<h2>Chequeo 8 · Con el objetivo en logaritmo</h2>
<div class="sourceCode" id="cb46"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb46-1"><a href=""></a><span class="im">from</span> sklearn.compose <span class="im">import</span> TransformedTargetRegressor</span>
<span id="cb46-2"><a href=""></a></span>
<span id="cb46-3"><a href=""></a>chequeo(<span class="st">"8 · + log del objetivo"</span>,</span>
<span id="cb46-4"><a href=""></a>        <span class="kw">lambda</span> m: TransformedTargetRegressor(</span>
<span id="cb46-5"><a href=""></a>            regressor<span class="op">=</span>Pipeline([(<span class="st">"pre"</span>, pre_escalado), (<span class="st">"reg"</span>, m)]),</span>
<span id="cb46-6"><a href=""></a>            func<span class="op">=</span>np.log1p, inverse_func<span class="op">=</span>np.expm1),</span>
<span id="cb46-7"><a href=""></a>        X, y)</span></code></pre></div>
<div class="terminal" data-nocopy="">
<pre>capítulo                 MSE lineal  R2 lineal   MSE red   R2 red
7 · + StandardScaler          33.30      0.455     35.23    0.449
8 · + log del objetivo        <span class="salida">29.59      0.581</span>    334.16   -3.704</pre>
</div>
<div class="alerta">
<p>La lineal firma su mejor resultado de la sesión —<span class="math inline">\(R^2 = 0{,}581\)</span>— y la red se desploma de 0,449 a <strong>−3,7</strong>.</p>
</div>
</section>
<section class="slide level2">
<h2>El mismo aviso, al revés</h2>
<div class="concepto">
<p>El logaritmo ayuda a la regresión lineal porque la relación entre las características y el precio se vuelve <strong>más lineal</strong> en esa escala. A la red no le hacía falta: ya podía curvarse sola, y lo único que le dimos fue un objetivo más difícil de deshacer.</p>
</div>
<div class="destacado">
<p>En el capítulo 7 el escalado salvó a la red y no le hizo nada a la lineal. Aquí pasa exactamente lo contrario. <strong>Cada paso hay que probarlo con el modelo que se va a usar</strong>, y quedarse con el que mejore.</p>
</div>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>9 · La foto completa</h1>
<p>Ocho capítulos, dos modelos, una tabla</p>
</section>
<section class="slide level2">
<h2>Todo el camino de una vez</h2>
<div class="terminal" data-nocopy="">
<pre>capítulo                          MSE lineal  R2 lineal    MSE red     R2 red
1a · Sin tocar nada                    error      error      error      error
1b · Solo las numéricas                error      error      error      error
2  · dropna sobre las numéricas        46.77      0.295   68165.39  -1015.810
3  · Partir bien (fuga o no)           37.39      0.440   71652.37  -1132.739
4  · + imputación con la mediana       37.39      0.440   71652.37  -1132.739
5  · + one-hot de todas                91.10     -0.242   18748.45   -389.281
6  · + agrupar categorías raras        33.30      0.455   26326.33   -377.586
7  · + escalado                        33.30      0.455      <span class="salida">35.23      0.449</span>
8  · + log del objetivo                <span class="salida">29.59      0.581</span>     334.16     -3.704</pre>
</div>
<p>Mismos dos modelos las ocho veces. Todo lo que cambia sale del preprocesamiento.</p>
</section>
<section class="slide level2">
<h2>Los dos recorridos no se parecen en nada</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>La regresión lineal</strong> Arranca en cuanto hay números y va mejorando poco a poco: 0,295 → 0,440 → 0,455 → 0,581. Solo tropieza una vez, con las 62 columnas del capítulo 5.</p>
</div>
<div class="tarjeta">
<p><strong>La red neuronal</strong> Inservible durante <strong>seis capítulos</strong> — R² entre −377 y −1132 — y de golpe útil al escalar. Después el logaritmo vuelve a hundirla.</p>
</div>
</div>
<div class="alerta">
<p>Si alguien mira solo la columna de la lineal, concluye que el escalado no sirve para nada. Si mira solo la de la red, concluye que sin escalar no se puede hacer nada. Las dos lecturas son falsas.</p>
</div>
</section>
<section class="slide level2">
<h2>Cinco cosas que deja esta tabla</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Cada paso resuelve un problema distinto</strong> Imputar recupera filas. Codificar añade información. Agrupar controla las columnas. Escalar habilita modelos. Transformar linealiza.</p>
</div>
<div class="tarjeta">
<p><strong>Un paso correcto puede empeorar</strong> El capítulo 5 hizo el <span class="math inline">\(R^2\)</span> negativo. La técnica estaba bien; faltaba mirar el resultado.</p>
</div>
<div class="tarjeta">
<p><strong>Y otro puede no cambiar nada</strong> El capítulo 3 dio cifras idénticas con fuga y sin ella. Se sigue la regla igual.</p>
</div>
<div class="tarjeta">
<p><strong>El mejor paso depende del modelo</strong> El escalado salvó a la red y no tocó a la lineal. El logaritmo, al revés.</p>
</div>
<div class="tarjeta">
<p><strong>Sin medir, nada de esto se ve</strong> Ocho chequeos son ocho oportunidades de descubrir que el último cambio fue en la dirección equivocada.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>El error que esta tabla evita</h2>
<div class="alerta">
<p>Un estudiante que pruebe la red en el capítulo 6 y vea un <span class="math inline">\(R^2\)</span> de −377 concluirá que “las redes no sirven para datos tabulares” o que “faltan datos”. Las dos conclusiones son falsas, y las dos son caras.</p>
</div>
<p>Lo que hacía falta era una línea: <code>StandardScaler()</code>.</p>
<div class="destacado">
<p>Por eso el orden es <strong>preparar los datos, medir, y solo entonces cambiar de modelo</strong>. Al revés, uno pasa semanas buscando arquitecturas para arreglar un problema de preprocesamiento.</p>
</div>
</section>
<section class="slide level2">
<h2>Lo que no hemos hecho</h2>
<div class="concepto">
<p>Ninguno de los dos modelos está <strong>afinado</strong>. La red lleva 32 neuronas y 2000 iteraciones porque hacía falta fijar algo, no porque sea la mejor opción; la lineal no tiene nada que afinar.</p>
</div>
<p>Con los datos ya preparados, un <span class="math inline">\(R^2\)</span> de 0,581 es el punto de partida, no el final. Elegir y ajustar el modelo es lo que viene después — y ahora se puede hacer sobre una base limpia.</p>
<p>Vamos a asomarnos un momento a eso.</p>
</section>
<section class="slide level2">
<h2>Y esto es a lo que se puede llegar</h2>
<p>Con los datos ya preparados, el resto del curso es <strong>elegir modelo y afinarlo</strong>. Un adelanto, sobre estos mismos 93 coches:</p>
<div class="terminal" data-nocopy="">
<pre>modelo                                          MSE       R2
LinearRegression + preprocesamiento (hoy)     33.30    0.455
Ridge, con alpha buscado                      35.19    0.567
Ridge + log del objetivo                      31.97    0.609
RandomForest afinado                          35.69    0.525
HistGradientBoosting afinado                  <span class="salida">31.68    0.640</span></pre>
</div>
<div class="concepto">
<p>De <strong>0,455 a 0,640</strong> sin tocar ni una línea del preprocesamiento. Eso es lo que aporta la parte del curso que viene después de hoy.</p>
</div>
</section>
<section class="slide level2">
<h2>Cómo se afina sin hacerse trampa</h2>
<div class="sourceCode" id="cb47"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb47-1"><a href=""></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> GridSearchCV</span>
<span id="cb47-2"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Ridge</span>
<span id="cb47-3"><a href=""></a></span>
<span id="cb47-4"><a href=""></a>busqueda <span class="op">=</span> GridSearchCV(</span>
<span id="cb47-5"><a href=""></a>    Pipeline([(<span class="st">"pre"</span>, pre_escalado), (<span class="st">"reg"</span>, Ridge())]),</span>
<span id="cb47-6"><a href=""></a>    {<span class="st">"reg__alpha"</span>: [<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">100</span>]},</span>
<span id="cb47-7"><a href=""></a>    cv<span class="op">=</span><span class="dv">5</span>, scoring<span class="op">=</span><span class="st">"r2"</span>)</span>
<span id="cb47-8"><a href=""></a></span>
<span id="cb47-9"><a href=""></a><span class="co"># la búsqueda va DENTRO de la validación cruzada, no fuera</span></span>
<span id="cb47-10"><a href=""></a>r <span class="op">=</span> cross_validate(busqueda, X, y, cv<span class="op">=</span><span class="dv">5</span>, scoring<span class="op">=</span>[<span class="st">"r2"</span>])</span>
<span id="cb47-11"><a href=""></a><span class="bu">print</span>(<span class="bu">round</span>(r[<span class="st">"test_r2"</span>].mean(), <span class="dv">3</span>))</span></code></pre></div>
<div class="alerta">
<p>Si se busca el mejor <code>alpha</code> con todos los datos y <strong>luego</strong> se mide con esos mismos datos, el resultado sale inflado: habríamos elegido el parámetro que mejor le venía al conjunto de prueba. Es fuga otra vez, ahora en los hiperparámetros.</p>
</div>
<p>Por eso se anida: en cada pliegue se busca con lo de dentro y se mide con lo de fuera. Se llama <strong>validación cruzada anidada</strong>.</p>
</section>
<section class="slide level2">
<h2>El giro final</h2>
<p>El mejor de la tabla, <code>HistGradientBoosting</code>, <strong>maneja los <code>NaN</code> y las categorías de forma nativa</strong>. No necesita ni imputar ni codificar.</p>
<div class="destacado">
<p>¿Sobraba entonces la sesión de hoy? Miren qué pasa si a ese mismo modelo le damos el dataset <strong>tal y como viene en el CSV</strong>.</p>
</div>
<div class="terminal" data-nocopy="">
<pre>HistGradientBoosting, todas las columnas del CSV      R2  <span class="salida">0.747</span>
HistGradientBoosting, sin Min.Price ni Max.Price     R2   0.599</pre>
</div>
<p>Un <span class="math inline">\(R^2\)</span> de 0,747: el mejor número de toda la sesión. Y completamente inútil.</p>
</section>
<section class="slide level2">
<h2>Por qué ese 0,747 es basura</h2>
<div class="terminal" data-nocopy="">
<pre>correlación con Price     Min.Price  0.971     Max.Price  0.982

Price - (Min.Price + Max.Price) / 2   -&gt;   error medio de 0.017</pre>
</div>
<div class="alerta">
<p><code>Price</code> <strong>es</strong> el promedio de <code>Min.Price</code> y <code>Max.Price</code>. El modelo no está prediciendo el precio: lo está leyendo de otras dos columnas que, en la vida real, no existirían hasta después de conocerlo.</p>
</div>
<div class="concepto">
<p>Ningún modelo, por potente que sea, va a avisar de esto. Quitar esas dos columnas fue una decisión nuestra, en la primera línea del primer chequeo, y es <strong>la más importante de toda la sesión</strong>.</p>
</div>
</section>
<section class="slide level2">
<h2>Lo que se llevan de hoy</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong>Lo que el modelo puede hacer por ustedes</strong> Imputar, codificar, escalar. Hay modelos modernos que se lo hacen solos, y cada año hacen más.</p>
</div>
<div class="tarjeta">
<p><strong>Lo que no va a hacer nunca</strong> Darse cuenta de que una columna es la respuesta disfrazada. Saber que aquel <code>NaN</code> significaba “sin airbag”. Decidir que 31 marcas en 93 coches son demasiadas.</p>
</div>
</div>
<div class="destacado">
<p>Lo primero se automatiza. Lo segundo es criterio, y es lo que van a estar construyendo durante todo el curso.</p>
</div>
</section></section>
<section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>Cierre</h1>

</section>
<section class="slide level2">
<h2>Lista de comprobación</h2>
<ol type="1">
<li>Mirar los datos: <code>shape</code>, <code>head</code>, <code>info</code>, <code>describe</code>.</li>
<li>Entender <strong>por qué</strong> falta lo que falta, antes de rellenarlo.</li>
<li><strong>Partir en entrenamiento y prueba.</strong></li>
<li>Imputar: mediana / moda / categoría nueva, con <code>fit</code> solo en entrenamiento.</li>
<li>Codificar: binaria → 0-1; ordinal → orden declarado; nominal → one-hot.</li>
<li>Vigilar la cardinalidad y agrupar las categorías raras.</li>
<li>Escalar si el modelo lo necesita.</li>
<li>Transformar lo muy sesgado.</li>
<li>Encapsular todo en un <code>Pipeline</code>.</li>
<li>Comparar contra una línea base y validar de forma cruzada.</li>
</ol>
</section>
<section class="slide level2">
<h2>Los tres errores que más van a ver</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><strong><code>fit</code> sobre todo el dataset</strong> El más común y el más silencioso: no da error, solo resultados demasiado buenos que luego no se reproducen.</p>
</div>
<div class="tarjeta">
<p><strong>Label encoding en nominales</strong> Le inventa un orden y unas distancias a lo que no las tiene.</p>
</div>
<div class="tarjeta">
<p><strong>One-hot sin mirar la cardinalidad</strong> Una columna de identificadores puede generar miles de columnas y hundir el modelo, como acabamos de ver.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Para practicar</h2>
<p>Repitan el recorrido completo sobre <strong>Ames Housing</strong>: 1.460 casas, 80 columnas, vacíos por todas partes y categóricas ordinales de verdad.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode numberSource python numberLines number-lines"><code class="sourceCode python"><span id="cb48-1"><a href=""></a><span class="im">from</span> sklearn.datasets <span class="im">import</span> fetch_openml</span>
<span id="cb48-2"><a href=""></a>ames <span class="op">=</span> fetch_openml(name<span class="op">=</span><span class="st">"house_prices"</span>, as_frame<span class="op">=</span><span class="va">True</span>).frame</span></code></pre></div>
<div class="destacado">
<p>Tres preguntas para guiarse: ¿qué columnas tienen tanto vacío que no vale la pena imputarlas? ¿Cuáles de las categóricas son ordinales de verdad? ¿Cuánto mejora el resultado al agrupar las categorías raras?</p>
</div>
</section></section>
<section class="title-slide slide level1 seccion center" data-background-color="#1553ad">
<h1>¿Preguntas?</h1>
<p>El cuaderno de la sesión está en la página del curso</p>
<p><a href="https://afpuertav.github.io/">afpuertav.github.io</a></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><span class="fcell f1">Andrés F. Puerta</span><span class="fcell f2">Preprocesamiento de datos</span><span class="fcell f3">Sesión 2</span></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="preprocesamiento_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="preprocesamiento_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="preprocesamiento_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="preprocesamiento_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="preprocesamiento_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="preprocesamiento_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="preprocesamiento_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="preprocesamiento_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="preprocesamiento_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="preprocesamiento_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="preprocesamiento_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"width":"normal"},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 760,

        // Factor of the display size that should remain empty around the content
        margin: 5.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <!--
      terminal-copy.html
      Botón de copiar para los bloques .terminal de las diapositivas.

      Cada bloque declara qué se copia en su atributo data-copy; si no lo declara,
      se copia el texto del <pre> quitando el prompt (span.prompt) y las líneas de
      salida marcadas con .salida.
    -->
    <script>
    (function () {
      function textoACopiar(term) {
        if (term.dataset.copy !== undefined) return term.dataset.copy;
        var pre = term.querySelector("pre");
        if (!pre) return term.textContent.trim();
        var clon = pre.cloneNode(true);
        // .prompt y .salida no forman parte del comando; los <a> de los números
        // de línea van vacíos, así que no estorban.
        clon.querySelectorAll(".prompt, .salida").forEach(function (n) { n.remove(); });
        return clon.textContent.replace(/^\s+|\s+$/g, "");
      }

      function copiar(texto) {
        if (navigator.clipboard && window.isSecureContext) {
          return navigator.clipboard.writeText(texto);
        }
        // Reserva para file:// y navegadores viejos
        return new Promise(function (resolver, rechazar) {
          var ta = document.createElement("textarea");
          ta.value = texto;
          ta.style.position = "fixed";
          ta.style.opacity = "0";
          document.body.appendChild(ta);
          ta.select();
          try {
            document.execCommand("copy") ? resolver() : rechazar();
          } catch (e) {
            rechazar(e);
          } finally {
            document.body.removeChild(ta);
          }
        });
      }

      function preparar() {
        // Los bloques de código de Quarto llevan el mismo botón que las terminales
        var bloques = document.querySelectorAll(".terminal, div.sourceCode");
        bloques.forEach(function (term) {
          if (term.querySelector(".term-copy")) return;
          if (term.dataset.nocopy !== undefined) return;

          var btn = document.createElement("button");
          btn.className = "term-copy";
          btn.type = "button";
          btn.textContent = "Copiar";
          btn.setAttribute("aria-label", "Copiar el comando al portapapeles");

          btn.addEventListener("click", function (ev) {
            ev.stopPropagation();
            ev.preventDefault();
            copiar(textoACopiar(term)).then(function () {
              btn.textContent = "¡Copiado!";
              btn.classList.add("copiado");
              setTimeout(function () {
                btn.textContent = "Copiar";
                btn.classList.remove("copiado");
              }, 1600);
            }, function () {
              btn.textContent = "Error";
              setTimeout(function () { btn.textContent = "Copiar"; }, 1600);
            });
          });

          term.appendChild(btn);
        });
      }

      if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", preparar);
      } else {
        preparar();
      }
      // reveal.js puede crear diapositivas de reserva; volvemos a pasar al arrancar
      window.addEventListener("load", preparar);
    })();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>